### PR TITLE
Add a guide for adding a JIRA prefix in the test name

### PR DESCRIPTION
**Pull request by HyukjinKwon**
As discussed in http://apache-spark-developers-list.1001551.n3.nabble.com/Adding-JIRA-ID-as-the-prefix-for-the-test-case-name-td28289.html

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @srowen, @hvanhovell, @dongjoon-hyun, @maropu, @gengliangwang

**Review by cloud-fan — APPROVED** [review]

**Review by srowen — APPROVED** [review]

**Review by gengliangwang — APPROVED** [review]

**Review by gatorsmile — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Review by maropu — APPROVED** [review]
Looks nice, @HyukjinKwon , thanks!

**Comment by HyukjinKwon** [comment]
Let me hold on a moment .. @zsxwing suggested to add for R, Python, Java too (see the discussion thread).

**Comment by keypointt** [comment]
LGTM :)

**Review by keypointt — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
I am going to merge this and run it separately for R, Python, and Java. cc @steveloughran

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon ! :)

**Pull request closed without merging**
