### PR TITLE
Add Shop section in the community page

### PR DESCRIPTION
**Pull request by gengliangwang**
To promote the Apache Spark swag, this PR adds a Shop section on the community page: https://spark.apache.org/community.html
The logo and the first sentence are from https://www.apache.org/foundation/buy_stuff.html

Here is a screenshot for preview:
Screen Shot 2022-06-14 at 14 45 52

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Comment by gengliangwang** [comment]
cc @mateiz as well

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by viirya — APPROVED** [review]

**Comment by yaooqinn** [comment]
late +1

**Comment by mateiz** [comment]
Looks good!

**Pull request closed without merging**
