### PR TITLE
Fix typo in contributing.md

### PR DESCRIPTION
**Pull request by dongjinleekr**
'h elping' -> 'helping'

### CODE REVIEW

**Review by srowen — CHANGES_REQUESTED** [review]
That's fine but please also regenerate the HTML.

**Comment by dongjinleekr** [comment]
Fixed.

**Comment by srowen** [comment]
You can close this now  @dongjinleekr -- I don't think it will auto-close since I had to do a rebase for some technical reasons. but it's in now.

**Comment by dongjinleekr** [comment]
Thanks, @srowen!!

**Pull request closed without merging**
