### PR TITLE
Fix  wrong issue link

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
Fix wrong issue link

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
oh wait, we should also update generated HTMLs too.

**Comment by AngersZhuuuu** [comment]
> oh wait, we should also update generated HTMLs too.

OK,  let me change it

**Comment by AngersZhuuuu** [comment]
> oh wait, we should also update generated HTMLs too.

updated and double checked.

**Review by srowen — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
+1, late LGTM.

**Pull request closed without merging**
