### PR TITLE
Fix signature description broken in PySpark API documentation in 2.2.2

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This PR proposes to fix signature description broken in PySpark API documentation in 2.2.2. See SPARK-24530.

Sphinx version was intentionally matched to reduce the diff.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @mengxr and @tgravescs

**Comment by tgravescs** [comment]
+1

**Comment by mengxr** [comment]
LGTM

**Comment by HyukjinKwon** [comment]
Merged Thanks @tgravescs and @mengxr.

**Pull request merged**
