### PR TITLE
Add news, release note, download link for Apache Spark 3.4.2

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
Vote Result: https://lists.apache.org/thread/nlk9n25cznksqqf0j9wxdxg62x8vtj87
Documentation: https://spark.apache.org/docs/3.4.2/
Binary: https://downloads.apache.org/spark/spark-3.4.2/
PySpark: https://pypi.org/project/pyspark/3.4.2/
Maven Central: https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.13/3.4.2/

Screenshot 2023-11-30 at 9 06 02 AM

Screenshot 2023-11-30 at 9 06 53 AM

Screenshot 2023-11-30 at 9 07 37 AM

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @sunchao ?

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Oh, thank you, @viirya !

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @sunchao .

**Comment by dongjoon-hyun** [comment]
Merged!

**Comment by dongjoon-hyun** [comment]
Hi, @gengliangwang and @Yikun

- @gengliangwang , could you update the search engine part, please?
- @Yikun , could you handle DockerHub image parts, please?

**Comment by gengliangwang** [comment]
@dongjoon-hyun sure, it is done.

**Comment by dongjoon-hyun** [comment]
Thank you so much, @gengliangwang !

**Pull request closed without merging**
