### PR TITLE
Regenerate PySpark documentation for Spark 3.2.0

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This PR regenerates PySpark documentation from the same tag. There was dependency missing during the documentation build, and many pages are malformed. For example

**Before:**

Screen Shot 2021-12-06 at 1 36 48 PM

**After:**
Screen Shot 2021-12-06 at 1 36 26 PM

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @gengliangwang @dongjoon-hyun @srowen FYI

**Comment by HyukjinKwon** [comment]
This, for example, also creates an image for plots too:
Screen Shot 2021-12-06 at 1 44 11 PM

**Comment by HyukjinKwon** [comment]
cc @gatorsmile and @mateiz too FYI

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Thanks.

Merged.

**Pull request closed without merging**
