### PR TITLE
Add a LTS release plan for 2.4.5/2.4.6

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR aims to add a LTS release plan for 2.4.5 and 2.4.6.
screen

### CODE REVIEW

**Review by srowen — APPROVED** [review]
I think it's OK but do we normally advertise this? Maybe we should.

**Comment by dongjoon-hyun** [comment]
Thank you! Yes. It will be helpful because it's LTS. Also, K8s users seems to need some answers on this.

**Comment by maropu** [comment]
Late LGTM, that info looks nice for users.

**Comment by dongjoon-hyun** [comment]
Thank you, @maropu !

**Review by HyukjinKwon — COMMENTED** [review]
+1 LGTM

**Pull request merged**
