### PR TITLE
Add Apache Spark 3.1.2 doc

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
- The first commit is adding the voted 3.1.2 doc and update `latest` link.
- The second commit is updating `facetFilter`.
```
-      'facetFilters': ["version:3.1.1"]
+      'facetFilters': ["version:3.1.2"]
```

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
@gengliangwang . This has the update for facetFilters. Could you check the second commit?

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya !

**Review by maropu — APPROVED** [review]
Thank you @dongjoon-hyun . I took a cursory look at this and lgtm.

**Comment by dongjoon-hyun** [comment]
Thank you, @maropu !

**Comment by dongjoon-hyun** [comment]
I'll merge this and proceed to the next steps. Thank you!

**Comment by HyukjinKwon** [comment]
👏

**Comment by maropu** [comment]
👏

**Review by gengliangwang — COMMENTED** [review]
Late LGTM! Thanks

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon and @gengliangwang !

**Pull request merged**
