### PR TITLE
Add Dilip Biswal to committers.md

### PR DESCRIPTION
**Pull request by dilipbiswal**
Add "Dilip Biswal" to committer list.

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Review by maropu — APPROVED** [review]
Congrats!

**Review by HeartSaVioR — APPROVED** [review]
Congrats!

**Comment by kiszk** [comment]
Congrats! I wanted to say it in person at SAIS2020.

**Review by kiszk — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Congrats @dilipbiswal

**Review by HyukjinKwon — APPROVED** [review]

**Comment by huaxingao** [comment]
congratulations!

**Comment by maropu** [comment]
@dilipbiswal Could you merge this by yourself for yoru practice?

**Comment by dilipbiswal** [comment]
@maropu Sure. Let me see how to do it.

**Review by viirya — APPROVED** [review]
Congrats!

**Comment by MaxGekk** [comment]
@dilipbiswal Congratulations!!!

**Pull request closed without merging**
