### PR TITLE
fix hardcoded jira issue number in link to SPIPs

### PR DESCRIPTION
**Pull request by koeninger**

### CODE REVIEW

**Comment by srowen** [comment]
Looks OK @koeninger except it looks like the temporary changes it made to serve the site locally got added to the pull request. I think you just want to revert everything but the 2 improvement files.

**Comment by koeninger** [comment]
Other way around, right?  Head has localhost:4000, the pr has spark.apache.org

The live site right now has localhost:4000

e.g.

http://spark.apache.org/sitemap.xml

**Comment by koeninger** [comment]
Looks like the localhost was introduced in commit fda1364c

**Comment by srowen** [comment]
Oh! yes not reading straight. Wow, that's my fault. I'll get that fixed straight away, thanks

**Comment by srowen** [comment]
This is merged. You may need to manually close it @koeninger

**Comment by koeninger** [comment]
Checked the live site, looks good, thanks.

**Pull request closed without merging**
