### PR TITLE
Add news, release note, download link for Apache Spark 3.4.1

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
- Vote Result: https://lists.apache.org/thread/pyby097xs0m8t9t755pwrpr9zydm7bop
- Documentation: https://spark.apache.org/docs/3.4.1/
- Binary: https://downloads.apache.org/spark/spark-3.4.1/
- PySpark: https://pypi.org/project/pyspark/3.4.1/
- Maven Central: https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.13/3.4.1/

Screenshot 2023-06-23 at 4 48 54 PM

Screenshot 2023-06-23 at 4 49 58 PM

Screenshot 2023-06-23 at 4 50 03 PM

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @viirya ?

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you!

**Comment by dongjoon-hyun** [comment]
Will double-check and announce it shortly.

**Comment by dongjoon-hyun** [comment]
Hi, @gengliangwang and @Yikun 

- @gengliangwang , could you update the search engine part, please?
- @Yikun , could you handle DockerHub image parts, please? To avoid the conflicts like the previous one, I didn't publish docker images intentionally.

**Comment by gengliangwang** [comment]
@dongjoon-hyun Thanks for working on the release!
I have updated and kicked off the crawler. It should be available in one hour.

**Comment by dongjoon-hyun** [comment]
Thank you so much always, @gengliangwang !

**Comment by Yikun** [comment]
> @Yikun , could you handle DockerHub image parts, please? To avoid the conflicts like the previous one, I didn't publish docker images intentionally.

- 3.4.1 dockerfiles merged in https://github.com/apache/spark-docker/pull/46
- 3.4.1 docker images published: https://github.com/apache/spark-docker/actions/runs/5367516994 to https://hub.docker.com/r/apache/spark/tags

**Pull request merged**
