### PR TITLE
Add Jiaan Geng to committer list

### PR DESCRIPTION
**Pull request by beliefer**
This PR used to add Jiaan Geng to committer list.

I generate the html and show the screenshot below.
image

### CODE REVIEW

**Comment by beliefer** [comment]
ping @zhengruifeng

**Comment by zhengruifeng** [comment]
you should add your name [here](https://github.com/apache/spark-website/blob/asf-site/committers.md?plain=1#L32)

**Comment by beliefer** [comment]
> you should add your name [here](https://github.com/apache/spark-website/blob/asf-site/committers.md?plain=1#L32)

Got it.

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
Congrats!

**Comment by peter-toth** [comment]
Congratulations!

**Comment by HeartSaVioR** [comment]
Congrats!

**Comment by beliefer** [comment]
@zhengruifeng @peter-toth @HeartSaVioR Thank you for all!

**Pull request merged**
