### PR TITLE
Document Spark 3.5 LTS period

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR aims to update Apache Spark versioning policy with Apache Spark 3.5 LTS period example.

### CODE REVIEW

**Review by yaooqinn — APPROVED** [review]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you so much, @yaooqinn !

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya , too.

**Review by mridulm — APPROVED** [review]
LGTM

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to asf-site.

**Comment by dongjoon-hyun** [comment]
Thank you, @mridulm and @HyukjinKwon !

**Pull request closed without merging**
