### PR TITLE
Auto update the copyright year 

### PR DESCRIPTION
**Pull request by wangyum**

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
Let's just take out the year? I don't think it has any value or significance

**Comment by wangyum** [comment]
OK. close it.

**Comment by srowen** [comment]
I was thinking to remove the year rather than update but either way, yes it doesn't matter to copyright

**Comment by wangyum** [comment]
Removed the copyright year.

**Comment by srowen** [comment]
I think it's fine. I think it doesn't matter either way

**Comment by wangyum** [comment]
I'm prefer keep the year:
image

**Pull request closed without merging**
