### PR TITLE
Add Chao Sun to committers

### PR DESCRIPTION
**Pull request by sunchao**

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Comment by sunchao** [comment]
Merged. Thanks @srowen !

**Comment by zero323** [comment]
Congrats @sunchao!

**Comment by c21** [comment]
Congrats @sunchao!

**Comment by sunchao** [comment]
Thanks @zero323 and @c21 !

**Comment by HeartSaVioR** [comment]
Wow! Congrats @sunchao!

**Comment by yaooqinn** [comment]
Congrats @sunchao!

**Comment by MaxGekk** [comment]
Congratulations @sunchao !

**Comment by sunchao** [comment]
Thanks all!

**Pull request closed without merging**
