### PR TITLE
Fix FAQ typo - Remove unnecessary occurrence of 'are'

### PR DESCRIPTION
**Pull request by checkaayush**

### CODE REVIEW

**Comment by srowen** [comment]
Sure, while you're at it, can you skim (or copy and paste into a grammar checker) more pages? it's useful if someone can make a pass over all the text once in a while.

**Comment by srowen** [comment]
Also @checkaayush you need to update the `.md` file and regenerate the site with Jekyll, not just edit `.html` directly.

**Comment by checkaayush** [comment]
@srowen Added the aforementioned change.

**Comment by srowen** [comment]
Merged -- @checkaayush you will have to close the PR manually though

**Pull request closed without merging**
