### PR TITLE
Update Dongjoon's information

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Review by gatorsmile — COMMENTED** [review]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @dongjoon-hyun !

**Comment by MaxGekk** [comment]
@dongjoon-hyun Congratulations!!!

**Comment by dongjoon-hyun** [comment]
Thanks, @MaxGekk !

**Comment by maropu** [comment]
oh, I just realized now! Congrats, @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thanks, @maropu ! :)

**Pull request merged**
