### PR TITLE
Add Apache Spark 3.4.2 documentation

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR aims to add Apache Spark 3.4.2 documentation first.

This is a simple import of the RC1 documentation.
- https://dist.apache.org/repos/dist/dev/spark/v3.4.2-rc1-docs/

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @LuciferYang and @yaooqinn ?

**Review by LuciferYang — APPROVED** [review]
LGTM

I sampled and inspected some changes that are only present in version 3.4.2, and the results are correct.

**Comment by dongjoon-hyun** [comment]
Thank you, @LuciferYang !

**Comment by yaooqinn** [comment]
Late LGTM

**Pull request closed without merging**
