### PR TITLE
Update ml-features.html

### PR DESCRIPTION
**Pull request by DataWanderer**

### CODE REVIEW

**Comment by DataWanderer** [comment]
As you see one of your team member @HyukjinKwon  has accepted this as an issue

**Comment by HyukjinKwon** [comment]
Please see https://github.com/apache/spark-website/pull/256#pullrequestreview-347745336. The PR should not be open here. Please stop creating PRs in this repository for this.

**Comment by HyukjinKwon** [comment]
I opened [a discussion thread to block](http://apache-spark-developers-list.1001551.n3.nabble.com/Block-a-user-from-spark-website-who-repeatedly-open-the-invalid-same-PR-td28759.html). Please stop causing overhead to the dev by repeatedly creating the invalid PRs on purpose.

**Comment by srowen** [comment]
Reported @DataWanderer to Github for abuse and a ban

**Pull request closed without merging**
