### PR TITLE
Organization update

### PR DESCRIPTION
**Pull request by zhengruifeng**

### CODE REVIEW

**Comment by yaooqinn** [comment]
Congrats！

**Review by yaooqinn — APPROVED** [review]

**Comment by Yikun** [comment]
Congrats!

**Comment by srowen** [comment]
Oh, just rerun jekyll to regenerate the .html (or you could just make the very simple change to the HTML file by hand too)

**Comment by zhengruifeng** [comment]
Thank you @srowen

**Comment by HeartSaVioR** [comment]
Congrats!

**Comment by dongjoon-hyun** [comment]
Congratulations, @zhengruifeng !

**Pull request merged**
