### PR TITLE
Add Jie Yang to committers

### PR DESCRIPTION
**Pull request by LuciferYang**

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @HyukjinKwon

**Comment by zhengruifeng** [comment]
congrats!

**Review by zhengruifeng — APPROVED** [review]

**Review by HeartSaVioR — APPROVED** [review]
Congrats!

**Review by wangyum — APPROVED** [review]

**Comment by yaooqinn** [comment]
Congrats！

**Review by yaooqinn — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by mridulm** [comment]
Congratulations !

**Review by mridulm — APPROVED** [review]

**Comment by roryqi** [comment]
Gongrats!

**Review by Yikun — APPROVED** [review]
Congrats!

**Review by roryqi — APPROVED** [review]

**Comment by huaxingao** [comment]
Congratulations!

**Review by huaxingao — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
Congrats! :)

**Comment by HyukjinKwon** [comment]
@LuciferYang feel free to merge it by yourself!

**Comment by Hisoka-X** [comment]
Congrats!

**Comment by LuciferYang** [comment]
Thanks all ~

**Pull request closed without merging**
