### PR TITLE
Add docs for Spark 2.3.2

### PR DESCRIPTION
**Pull request by jerryshao**
Add Spark 2.3.2 release document. Please help to review.

### CODE REVIEW

**Comment by jerryshao** [comment]
CC @srowen @dongjoon-hyun @HyukjinKwon please help to review. Thanks!

**Review by srowen — APPROVED** [review]
It's hard to do more than eyeball it but looks reasonable to me, especially these first few files, and in comparison to https://github.com/apache/spark-website/commit/e10014632b2101ae67dba2b607bd4259ee3ee53c

**Review by HyukjinKwon — APPROVED** [review]

**Comment by jerryshao** [comment]
Thanks for the review. Will the website automatically be updated after this PR is merged?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.
Python API doc is also generated correctly.

**Comment by HyukjinKwon** [comment]
> Thanks for the review. Will the website automatically be updated after this PR is merged?

Yup.

**Comment by jerryshao** [comment]
Thanks guys, I'm going to merge the PR to see if everything is landing.

**Comment by jerryshao** [comment]
PR is merged, but it still takes time to sync.

**Pull request closed without merging**
