### PR TITLE
Make 2.4.8 as EOL release

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
We finished a long journey for 2.4 line. This will make the EOL of 2.4 line officially in our website.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @srowen , @HyukjinKwon , @viirya , @maropu , @cloud-fan

**Review by viirya — APPROVED** [review]
lgtm

**Comment by maropu** [comment]
LGTM

**Comment by viirya** [comment]
Thanks @dongjoon-hyun and @maropu! Merging to asf-site!

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya and @maropu !

**Comment by HyukjinKwon** [comment]
👍

**Pull request closed without merging**
