### PR TITLE
Add Kent Yao to committers

### PR DESCRIPTION
**Pull request by yaooqinn**

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
Congrats @yaooqinn!

**Review by HeartSaVioR — APPROVED** [review]
Congrats!

**Comment by MaxGekk** [comment]
@yaooqinn Congratulations!!!

**Comment by wangyum** [comment]
Congrats!

**Comment by Ngone51** [comment]
Congrats @yaooqinn!

**Comment by viirya** [comment]
Congrats!

**Review by viirya — APPROVED** [review]

**Comment by huaxingao** [comment]
Congrats!

**Review by maropu — APPROVED** [review]
Congrats, @yaooqinn !

**Comment by HeartSaVioR** [comment]
Go test with your new ability to push! :)

**Comment by yaooqinn** [comment]
https://whimsy.apache.org/roster/committer/yao seems that my account hasn't been sync to Spark yet.

**Comment by happytofly** [comment]
Congrats, @yaooqinn !

**Comment by tclzju** [comment]
Congrats, bro @yaooqinn

**Comment by yaooqinn** [comment]
Thanks to everyone for your congrats.

**Comment by hzxiongyinke** [comment]
Congrats！

**Comment by zhengruifeng** [comment]
Congrats!

**Pull request closed without merging**
