### PR TITLE
Regenerate PySpark API documentation for Spark 3.2.1

### PR DESCRIPTION
**Pull request by xinrong-meng**
This PR regenerates PySpark API documentation for Spark 3.2.1.

Specifically, files under https://github.com/apache/spark-website/tree/asf-site/site/docs/3.2.1/api/python have been updated.

Currently, API of pandas API on Spark 3.2.1 are not associated with links, for example, API under https://spark.apache.org/docs/latest/api/python/reference/pyspark.pandas/series.html. So we wanted to regenerate it with correct dependencies.

How it gets updated:
- Generated docs under spark/python/doc against `v3.2.1` Spark
- Copy generated files from `spark/python/docs/build/html` to `spark-website/site/docs/3.2.1/api/python`.

### CODE REVIEW

**Comment by srowen** [comment]
Out of curiosity what creates all the changes - is it just formatting or any substantive change?

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
This is wrong, isn't it? @xinrong-databricks 
```
- <title>abc &#8212; PySpark 3.2.1 documentation</title>
+ <title>abc &#8212; PySpark master documentation</title>
```

cc @HyukjinKwon and @gengliangwang

**Review by HyukjinKwon — COMMENTED** [review]
We should regenerate the docs by setting `GIT_HASH` and `RELEASE_VERSION` environments properly (see https://github.com/apache/spark/blob/master/python/docs/source/conf.py). BTW, I wonder why this failed to generate the docs this time .. I fixed it here https://github.com/apache/spark/commit/03750c046b55f60b43646c8108e5f2e540782755

**Comment by gengliangwang** [comment]
> Out of curiosity what creates all the changes - is it just formatting or any substantive change?

Same question here. 
As many committers are watching this repo closely, @xinrong-databricks it would be great if you provide a summary of the changes in the PR description.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by xinrong-meng** [comment]
Sorry for the confusion. I added PR descriptions. Let me know if there are any questions.

FYI @HyukjinKwon @gengliangwang @srowen @dongjoon-hyun

**Comment by srowen** [comment]
It's hard to evaluate by looking at the diff but if it was merely regenerated from the 3.2.1 release to fix rendering of links, that seems OK

**Comment by HyukjinKwon** [comment]
Merged.

**Pull request closed without merging**
