### PR TITLE
Fix nit in 2-1-3 release page

### PR DESCRIPTION
**Pull request by xuanyuanking**
Thanks for @eric-buaa-cn reporting this.
Just a nit in 2-1-3 release page.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
@xuanyuanking, mind if I ask double check like by `grep`? Seems similar changes were made like two days ago and I think it's better to double check.

**Comment by HyukjinKwon** [comment]
LGTM

**Comment by xuanyuanking** [comment]
Thanks for your remind! There's also two nits in `news`.

**Comment by HyukjinKwon** [comment]
I manually squshed the commits and merged - https://github.com/apache/spark-website/commit/8857572dfd58941c83c6cc903d1922631a20fdfb. Mind manually closing this please?

**Comment by xuanyuanking** [comment]
Thanks for your help.

**Pull request closed without merging**
