### PR TITLE
Add Huaxin Gao to committers.md

### PR DESCRIPTION
**Pull request by huaxingao**

### CODE REVIEW

**Review by srowen — APPROVED** [review]
Go ahead and try the commit bit and merge it.

**Review by maropu — APPROVED** [review]
Congrats!

**Review by viirya — APPROVED** [review]
Congrats!

**Review by HeartSaVioR — APPROVED** [review]
Congrats!

**Comment by viirya** [comment]
@srowen, @huaxingao seems not been added into https://github.com/orgs/apache/teams/spark-committers/members yet?

**Comment by HeartSaVioR** [comment]
She's added in the roaster. http://people.apache.org/committer-index.html

Probably she didn't setup ASF Gitbox yet?

**Review by HyukjinKwon — APPROVED** [review]
Congrats!

**Comment by huaxingao** [comment]
Thanks everyone!

**Pull request closed without merging**
