### PR TITLE
Add 3.5.2 Documentation

### PR DESCRIPTION
**Pull request by yaooqinn**
```
svn co https://dist.apache.org/repos/dist/dev/spark/v3.5.2-rc5-docs/
cd v3.5.2-rc5-docs
cp -R _site ~/spark-website/site/docs/3.5.2
## _sources is deleted
find . -name _sources | xargs rm -rf
```

### CODE REVIEW

**Comment by yaooqinn** [comment]
PyPI and CRAN might be delayed.

## Upload to PyPI

https://github.com/pypi/support/issues/4529

## Publish to CRAN

image

**Comment by yaooqinn** [comment]
cc @dongjoon-hyun @cloud-fan @HyukjinKwon thanks

**Comment by HyukjinKwon** [comment]
I think we stopped releasing on CRAN for SparkR. It should be fine.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Thank you, @yaooqinn . Now, it's accessible.

- https://spark.apache.org/docs/3.5.2/

Screenshot 2024-08-11 at 11 07 47

**Comment by yaooqinn** [comment]
Thank you @HyukjinKwon @dongjoon-hyun

**Pull request closed without merging**
