### PR TITLE
Add Yi Wu to committers' list

### PR DESCRIPTION
**Pull request by Ngone51**

### CODE REVIEW

**Comment by yaooqinn** [comment]
Congrats @Ngone51

**Review by yaooqinn — APPROVED** [review]

**Comment by Ngone51** [comment]
Thanks, Congrats you too :)

**Comment by MaxGekk** [comment]
@Ngone51 Congratulations!!!

**Review by HyukjinKwon — APPROVED** [review]
Congrats!

**Review by HeartSaVioR — APPROVED** [review]
Congrats!

**Review by yaooqinn — APPROVED** [review]

**Comment by Ngone51** [comment]
Thank you guys @MaxGekk @yaooqinn @HyukjinKwon @HeartSaVioR

**Comment by viirya** [comment]
Congrats!

**Review by viirya — APPROVED** [review]

**Comment by huaxingao** [comment]
Congrats!

**Review by maropu — APPROVED** [review]
Congrats, @Ngone51 !

**Comment by HeartSaVioR** [comment]
Go test with your new ability to push! :)

**Comment by Ngone51** [comment]
Thanks :) @viirya @huaxingao @maropu

**Comment by Ngone51** [comment]
> Go test with your new ability to push! :)

I'm still waiting for the Apache account...

**Comment by zero323** [comment]
Congratulations @Ngone51

**Comment by Ngone51** [comment]
@zero323  Thanks, Congrats you too :)

**Comment by zhengruifeng** [comment]
Congrats!

**Pull request closed without merging**
