### PR TITLE
Add docs for Apache Spark 2.4.8

### PR DESCRIPTION
**Pull request by viirya**
Add docs for Apache Spark 2.4.8

### CODE REVIEW

**Comment by viirya** [comment]
cc @dongjoon-hyun @srowen @HyukjinKwon

**Comment by srowen** [comment]
As far as I can see, looks reasonable.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by viirya** [comment]
Thanks @srowen @dongjoon-hyun! Merging to asf-site.

**Comment by HyukjinKwon** [comment]
Awesome!

**Pull request closed without merging**
