### PR TITLE
Add Liang-Chi Hsieh to committer list

### PR DESCRIPTION
**Pull request by viirya**

### CODE REVIEW

**Review by srowen — APPROVED** [review]
Feel free to use `./merge_pr.py` to merge it! Ask if you have any problems setting up remotes, etc to make that work.

**Comment by viirya** [comment]
I set my remotes like:

```
apache  https://github.com/apache/spark-website.git (fetch)
apache  https://github.com/apache/spark-website.git (push)
apache-github   git://github.com/apache/spark-website (fetch)
apache-github   git://github.com/apache/spark-website (push)
origin  git@github.com:viirya/spark-website.git (fetch)
origin  git@github.com:viirya/spark-website.git (push)
upstream        https://github.com/apache/spark-website.git (fetch)
upstream        https://github.com/apache/spark-website.git (push)
```

But it always fails when pushing to remote:
```
Merge complete (local ref PR_TOOL_MERGE_PR_212_ASF-SITE). Push to apache? (y/n): y
git push apache PR_TOOL_MERGE_PR_212_ASF-SITE:asf-site
Username for 'https://github.com': viirya
Password for 'https://viirya@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/apache/spark-website.git/'
```

**Comment by maropu** [comment]
Congrats! super well deserved!! (btw, the setting looks ok to me and the account setup's ok, too:... https://github.com/orgs/apache/teams/spark-committers

**Review by maropu — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by srowen** [comment]
Hm, here are my remotes @viirya :
```
apache	https://github.com/apache/spark-website.git (fetch)
apache	https://github.com/apache/spark-website.git (push)
apache-github	git://github.com/apache/spark-website (fetch)
apache-github	git://github.com/apache/spark-website (push)
origin	https://github.com/srowen/spark-website.git (fetch)
origin	https://github.com/srowen/spark-website.git (push)
upstream	https://github.com/apache/spark-website.git (fetch)
upstream	https://github.com/apache/spark-website.git (push)
```

I have also set a `GITHUB_OAUTH_KEY` in my env; that may be necessary to push from the command line.

**Comment by viirya** [comment]
oh, I don't set `GITHUB_OAUTH_KEY` as from `merge_pr.py` it sounds not necessary.

**Comment by srowen** [comment]
I think it may be necessary, or else I'm not sure how github can authenticate the pushes that the script invokes.

**Comment by viirya** [comment]
let me try it.

**Comment by HyukjinKwon** [comment]
Hm, remote looks correct and seems it should work.

**Comment by viirya** [comment]
Same failure after setting up `GITHUB_OAUTH_KEY`.

**Comment by ueshin** [comment]
I guess you need to setup an access token and use the token as the password.

**Comment by HyukjinKwon** [comment]
Oh, yes seems @ueshin's comment is correct.

**Comment by viirya** [comment]
Yes, @ueshin you are correct!

**Comment by viirya** [comment]
Thanks you all!

**Comment by kiszk** [comment]
congrats!

**Comment by dongjoon-hyun** [comment]
Congratulation, @viirya ! 😄

**Comment by viirya** [comment]
@kiszk @dongjoon-hyun Thanks!

**Comment by gatorsmile** [comment]
Congratulations!

**Comment by viirya** [comment]
Thanks! @gatorsmile

**Comment by BryanCutler** [comment]
Congrats @viirya !

**Comment by viirya** [comment]
Thanks! @BryanCutler

**Pull request closed without merging**
