### PR TITLE
Add the 2.1.2 docs

### PR DESCRIPTION
**Pull request by holdenk**
This adds the 2.1.2 docs.

### CODE REVIEW

**Comment by holdenk** [comment]
cc @felixcheung

**Review by felixcheung — APPROVED** [review]
spot-checked a few things, can't review in details since github won't show it.

I think this is safe to merge ahead of other PRs

**Comment by holdenk** [comment]
Do we have a merge script for the spark-website or is just a manual rebase/squash push to ASF?

**Comment by HyukjinKwon** [comment]
I remember we should manually push.

**Comment by holdenk** [comment]
Merged to asf-site.

**Pull request closed without merging**
