### PR TITLE
Use a direct AMPLab link for ec2-script in FAQ

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR aims to fix the followings.
- Remove `site/docs/2.1.1/ec2-scripts.md`
- Use a direct AMPLab link for `ec2-script` in FAQ

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
In `spark`, `ec2-scripts.html` is generated correctly like `running-on-yarn.html`.

However, the following `ec2-scripts.html` shows 404 error in RC6 docs while `running-on-yarn.html` works.
- https://people.apache.org/~pwendell/spark-releases/spark-2.2.0-rc6-docs/ec2-scripts.html
- https://people.apache.org/~pwendell/spark-releases/spark-2.2.0-rc6-docs/running-on-yarn.html

It's the same on `Apache Spark` home page on (2.1.1).
- http://spark.apache.org/docs/latest/running-on-yarn.html
- http://spark.apache.org/docs/latest/ec2-scripts.html

**Comment by dongjoon-hyun** [comment]
Surprisingly, it seems this happened before continuously and and were fixed by manually.

```bash
~/spark-website$ git log --oneline | grep 'ec2'
8d5d77c65 Manually patch ec2-scripts.html file, missing from 2.0.1, 2.0.2 docs
b2cf71427 Hot-fix ec2-scripts.html in Spark docs/2.0.0, which for some reason built correctly in 2.0.0-preview, builds in master, but didn't deploy in 2.0.0
```

```
~/s/s/docs$ ls 2.0.1/ec2-scripts.html
2.0.1/ec2-scripts.html
~/s/s/docs$ ls 2.0.2/ec2-scripts.html
2.0.2/ec2-scripts.html
~/s/s/docs$ ls 2.1.0/ec2-scripts.html
2.1.0/ec2-scripts.html
~/s/s/docs$ ls 2.1.1/ec2-scripts.html
ls: 2.1.1/ec2-scripts.html: No such file or directory
```

**Review by srowen — APPROVED** [review]
This looks fine. Yeah I don't know what's wrong with this file, and I remember it failed to generate HTML in the past. We may have to patch for 2.2 too.

This doc is pretty obsolete anyway, so I'd also recommend just deleting it and links to it in the source docs for `master`.

**Comment by dongjoon-hyun** [comment]
Thank you for review, @srowen .
I'll create a PR to remove  `ec2-scripts.md` for `master`.
In the master, there is no link to `ec2-scripts.md`. The only usage seems to be FAQ here.

**Comment by srowen** [comment]
Thanks. Actually, I suppose it's better to just point to the URL that the doc redirects to, then, in faq.md? it redirects to https://github.com/amplab/spark-ec2#readme

**Comment by dongjoon-hyun** [comment]
Sure!

**Review by srowen — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you again, @srowen .

**Pull request merged**
