### PR TITLE
[SPARK-18323][ML][DOC] Updated MLlib site for 2.1

### PR DESCRIPTION
**Pull request by jkbradley**
Changes:
* Updated "Calling MLlib in Python" example to use DataFrame-based API
* Slightly better organization for "Algorithms" list. Divide into 3 sections: ML algorithms (basic ML algs), ML workflows (featurization, Pipelines, tuning), ML utilities (linalg, stats)

### CODE REVIEW

**Comment by jkbradley** [comment]
CC: @srowen @yanboliang @mengxr

**Comment by srowen** [comment]
Seems fine. If these changes require 2.1 we'll want to hold on to this until the release

**Comment by jkbradley** [comment]
They actually don't require 2.1, so no worries there.

**Comment by yanboliang** [comment]
This looks good to me. Thanks.

**Comment by jkbradley** [comment]
@srowen I think I used to have merge access to this repo but don't anymore.  How do we merge things to it?  Or do I push directly to upstream/asf-site?

**Comment by jkbradley** [comment]
Nevermind, I finally remembered!

**Pull request merged**
