### PR TITLE
Apache Spark 2.3.0 Release: Generated Docs

### PR DESCRIPTION
**Pull request by sameeragarwal**
This patch adds the generated docs (based off of 2.3.0-rc5: https://dist.apache.org/repos/dist/dev/spark/v2.3.0-rc5-docs/_site/index.html) for the next Apache Spark 2.3.0 release.

### CODE REVIEW

**Review by gatorsmile — COMMENTED** [review]
LGTM. I clicked all the links of the front pages and scans the linked files. All of them work well.

**Comment by srowen** [comment]
I merged this one too. @sameeragarwal you'll have to close the PR manually.

**Comment by sameeragarwal** [comment]
@srowen is this merged? I don't see a commit yet.

**Comment by srowen** [comment]
Yes the sync between the ASF git repo and Github frequently misses. It happened earlier. The next commit will probably push it. In a pinch we can push a blank commit.

**Pull request closed without merging**
