### PR TITLE
Add note on generative tooling to developer tools

### PR DESCRIPTION
**Pull request by zero323**
This PR adds notes on generative tooling and link to the relevant ASF policy.

As requested in comments to https://github.com/apache/spark/pull/42469

### CODE REVIEW

**Comment by zero323** [comment]
cc @srowen @zhengruifeng

**Review by srowen — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Review by zhengruifeng — APPROVED** [review]

**Comment by zero323** [comment]
Thanks @srowen @viirya @zhengruifeng

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM.

**Review by HyukjinKwon — COMMENTED** [review]
LGTM

**Comment by yaooqinn** [comment]
LGTM

**Pull request closed without merging**
