### PR TITLE
Release process updates

### PR DESCRIPTION
**Pull request by felixcheung**
Update release process

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
Looks reasonable.

**Comment by felixcheung** [comment]
https://github.com/apache/spark/pull/19754

**Comment by srowen** [comment]
BTW @felixcheung did you have more updates on this one?

**Comment by felixcheung** [comment]
Nope, that’s it, ready to merge if approved.

**Comment by srowen** [comment]
Done @felixcheung ; you'll need to close this manually because I rebased it.

**Comment by felixcheung** [comment]
thanks!

**Comment by sameeragarwal** [comment]
@holdenk @felixcheung @srowen just wanted to call this out and thank you all for taking time to add these extremely detailed instructions about the overall release process. Thanks!

**Pull request closed without merging**
