### PR TITLE
Fix the names in Credits in 2.0 release note

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This PR fixes the names in `Credits`.

The names were retrieved from Github profile (after checking the contributions and matching IDs) and [known_translations](https://github.com/apache/spark/blob/master/dev/create-release/known_translations).

The updated names are as below:

``` bash
aokolnychyi -> Anton Okolnychyi
bomeng -> Bo Meng
catapan -> Cedar Pan
koeninger -> Cody Koeninger # it was "cody koeninger"
felixcheung -> Felix Cheung
frreiss -> Fred Reiss
gatorsmile -> Xiao Li
hyukjinkwon -> Hyukjin Kwon
jeanlyn -> Jean Lyn
jerryshao -> Saisai Shao
jliwork -> Jia Li
krishnakalyan3 -> Krishna Kalyan
lfzCarlosC -> Fonso Li
lgieron -> Łukasz Gieroń
mark800 -> Mark Yang
mathieulongtin -> Mathieu Longtin # it was "mathieu longtin"
mwws -> Wei Mao
pierre-borckmans -> Pierre Borckmans
poolis -> Greg Michalopoulos
proflin -> Liwei Lin
agsachin -> Sachin Aggarwal
scwf -> Wang Fei
sethah -> Seth Hendrickson
shijinkui -> Shi Jinkui
sureshthalamati -> Suresh Thalamati
tedyu -> Ted Yu
tmnd1991 -> Antonio Murgia
vijaykiran -> Vijay Kiran
wangmiao1981 -> Miao Wang # it was "wm624@hotmail.com"
xwu0226 -> Xin Wu
zero323 -> Maciej Szymkiewicz
```

These names were unable to be identified:
- Can be identified but contributions not found
  
  ```
  hushan
  ```
- Can't see the real name.
  
  ```
  dding3 
  depend
  fwang1
  huangzhaowei
  hushan
  jayadevanmurali 
  junhao 
  kaklakariada
  mcheah
  movelikeriver
  petermaxlee
  prabs
  rotems
  sandy
  seddonm1
  sharkd
  thomastechs
  wangfei 
  wangyang
  wujian
  yzhou2001
  zhonghaihua
  zhuol
  zlpmichelle
  ```
- Can't find the Github profile
  
  ```
  echo2mei
  guoxu1231
  meiyoula
  nfraison
  oraviv
  peng.zhang
  pshearer 
  ```

This was sorted in an order of uppercases, lowercases and other language or special characters.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@rxin I just wonder the updated (and non-duplicated) names should be added in [known_translations](https://github.com/apache/spark/blob/master/dev/create-release/known_translations).

**Comment by srowen** [comment]
Sounds good @HyukjinKwon but can you also regenerate the HTML with `jekyll build`? I can do this separately if it's any trouble.

**Comment by HyukjinKwon** [comment]
I will! Sorry I didn't know I should build the HTML.

**Comment by HyukjinKwon** [comment]
I will close this as it seems merged but does not get closed (because it is not the master but a branch??). I will reopen if there is any problem.

**Comment by HyukjinKwon** [comment]
BTW, if anyone thinks the list above should be added into known_translations, please let me know. I will do (or I don't mind if anyone does this).

**Pull request closed without merging**
