### PR TITLE
Update committer page

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This PR updates the committer list (adding me).

### CODE REVIEW

**Review by srowen — APPROVED** [review]
Do you want to try pushing it? it's manual compared to the `spark` repo, which has a helper script. You should be able to push your commit to the `apache` remote, `asf-site` branch: `git push apache <hash>:asf-site`.

**Comment by HyukjinKwon** [comment]
Sure, let me give a try. Thank you.

**Comment by HyukjinKwon** [comment]
It looks I am getting ...

```
remote: Permission to apache/spark-website.git denied to HyukjinKwon.
fatal: unable to access 'https://github.com/apache/spark-website.git/': The requested URL returned error: 403
```

Do I maybe need to setup anything else manually for my account in Git?

**Comment by srowen** [comment]
None of us can push to the github repo. You have to push to the apache git repo, which is then mirrored.

```
$ git remote -v
apache	https://git-wip-us.apache.org/repos/asf/spark-website.git (fetch)
apache	https://git-wip-us.apache.org/repos/asf/spark-website.git (push)
origin	https://github.com/srowen/spark-website.git (fetch)
origin	https://github.com/srowen/spark-website.git (push)
upstream	https://github.com/apache/spark-website.git (fetch)
upstream	https://github.com/apache/spark-website.git (push)
```

**Comment by HyukjinKwon** [comment]
Thank you @srowen. It looks done correctly. Will take a look about this by myself.

**Pull request merged**
