### PR TITLE
Add Gengliang Wang to committer list

### PR DESCRIPTION
**Pull request by gengliangwang**

### CODE REVIEW

**Review by srowen — APPROVED** [review]
Feel free to merge with `./merge_pr.py` after you have set up your github remotes and OAUTH token.

**Comment by gatorsmile** [comment]
Congratulations!

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
Congratulation, @gengliangwang ! 😄

**Review by zhengruifeng — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Review by wangyum — APPROVED** [review]

**Comment by MaxGekk** [comment]
@gengliangwang Congratulations!!! Will ping you ;-)

**Comment by gengliangwang** [comment]
Thank you! @srowen  @gatorsmile @dongjoon-hyun @MaxGekk

**Comment by maropu** [comment]
oh, congrats!!

**Pull request closed without merging**
