### PR TITLE
Add docs for Apache Spark 3.1.1

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This PR aims to add Apache Spark 3.1.1 documentation
- Add `v3.1.1-rc3-docs/_site` into `site/docs/3.1.1`.
- Change `latest` to `3.1.1`

### CODE REVIEW

**Review by srowen — APPROVED** [review]
Skimming it, looks OK.

**Review by maropu — APPROVED** [review]

**Review by gatorsmile — APPROVED** [review]
Wish the search box can work well!

**Review by gengliangwang — APPROVED** [review]

**Comment by gatorsmile** [comment]
https://spark.apache.org/docs/3.1.1/ works, but https://spark.apache.org/docs/latest/ misses the menu

**Comment by gatorsmile** [comment]
https://spark.apache.org/docs/latest/api/python/index.html points to an old python page. https://spark.apache.org/docs/3.1.1/api/python/index.html is the right one.

**Comment by gatorsmile** [comment]
Both issues are gone after I cleaned the cache. 

The search box is not working. @gengliangwang is asking the algolia team to trigger the crawl. https://github.com/algolia/docsearch-configs/pull/3391#issuecomment-789083896

**Comment by gengliangwang** [comment]
> Both issues are gone after I cleaned the cache.

Yes, there is cache in browsers. If you don't see https://spark.apache.org/docs/latest/ updated, try hard refresh (e.g. `cmd + shift +r` in Chome, mac os)

**Pull request merged**
