### PR TITLE
Add Max Gekk to committers

### PR DESCRIPTION
**Pull request by MaxGekk**

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
Congrats Max!

**Review by HeartSaVioR — APPROVED** [review]
Congrats!

**Comment by wangyum** [comment]
Congrats!

**Review by dongjoon-hyun — APPROVED** [review]
Congratulation, @MaxGekk !

**Comment by yaooqinn** [comment]
Congrats!

**Comment by viirya** [comment]
Congrats!

**Comment by huaxingao** [comment]
Congrats!

**Comment by maropu** [comment]
Congrats, @MaxGekk !

**Comment by zhengruifeng** [comment]
Congratulations!

**Pull request closed without merging**
