### PR TITLE
Add Zhenhua Wang to the list of committers

### PR DESCRIPTION
**Pull request by wzhfy**

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
:+1:

**Comment by HyukjinKwon** [comment]
@wzhfy, would you like to push it by yourself or would I?

**Comment by wzhfy** [comment]
@HyukjinKwon Would you please push it? Thanks a lot!

**Comment by HyukjinKwon** [comment]
I have just pushed manually - https://github.com/apache/spark-website/commit/114925632af194d6dd7f2ca253c547e79aeb9364. You could close this :).

**Pull request closed without merging**
