### PR TITLE
Fix URL in twitter:image of home page

### PR DESCRIPTION
**Pull request by gengliangwang**
The URL of `twitter:image` misses one slash. This PR is to fix it.

### CODE REVIEW

**Comment by gengliangwang** [comment]
cc @gatorsmile

**Review by yaooqinn — APPROVED** [review]

**Comment by srowen** [comment]
(There's no markdown template for layouts right?)
Any other occurences? might look for this variable followed by no slash, just to make sure there aren't others

**Review by srowen — APPROVED** [review]
(I checked and there isn't another occurrence)

**Comment by gengliangwang** [comment]
> Any other occurences? might look for this variable followed by no slash, just to make sure there aren't others

@srowen I checked. This is the only bug I can find.

**Pull request merged**
