### PR TITLE
Add 3.0.2 doc

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR aims to add Apache Spark 3.0.2 documentation
- Add `v3.0.2-rc1-docs/_site` into `site/docs/3.0.2`.
- Change `latest` to `3.0.2`

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @srowen , @HyukjinKwon , @viirya , @maropu

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you so much!

**Comment by maropu** [comment]
late lgtm. Thanks for the manager!

**Comment by HyukjinKwon** [comment]
LGTM!

**Comment by dongjoon-hyun** [comment]
Thank you, @maropu and @HyukjinKwon !

**Pull request merged**
