### PR TITLE
Add Yuming Wang to committer list

### PR DESCRIPTION
**Pull request by wangyum**

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
Yes! Congratulation, @wangyum !

**Comment by maropu** [comment]
Congrats!

**Comment by AngersZhuuuu** [comment]
Congratulation!

**Review by srowen — APPROVED** [review]
Feel free to merge with `./merge_pr.py` once your remotes are setup, and github auth key.

**Comment by wangyum** [comment]
I setup 2-faced auth and use access token. But it always fails when pushing to remote: 
`remote: Permission to apache/spark-website.git denied to wangyum.`

```
yumwang@ubuntu-3513086:~/spark-website$ ./merge_pr.py
git rev-parse --abbrev-ref HEAD
Which pull request would you like to merge? (e.g. 34): 213

=== Pull Request #213 ===
title	Add Yuming Wang to committer list
source	wangyum/add-committer
target	asf-site
url	https://api.github.com/repos/apache/spark-website/pulls/213

Proceed with merging pull request #213? (y/n): y
git fetch apache-github pull/213/head:PR_TOOL_MERGE_PR_213
From git://github.com/apache/spark-website
 * [new ref]             refs/pull/213/head -> PR_TOOL_MERGE_PR_213
git fetch apache asf-site:PR_TOOL_MERGE_PR_213_ASF-SITE
From https://github.com/apache/spark-website
 * [new branch]          asf-site   -> PR_TOOL_MERGE_PR_213_ASF-SITE
git checkout PR_TOOL_MERGE_PR_213_ASF-SITE
Switched to branch 'PR_TOOL_MERGE_PR_213_ASF-SITE'
['git', 'merge', 'PR_TOOL_MERGE_PR_213', '--squash']
Automatic merge went well; stopped before committing as requested
['git', 'log', 'HEAD..PR_TOOL_MERGE_PR_213', '--pretty=format:%an <%ae>']
Enter primary author in the format of "name <email>" [Yuming Wang <yumwang@ebay.com>]:
['git', 'log', 'HEAD..PR_TOOL_MERGE_PR_213', '--pretty=format:%h [%an] %s']
['git', 'commit', '--author="Yuming Wang <yumwang@ebay.com>"', '-m', u'Add Yuming Wang to committer list', '-m', u'', '-m', 'Author: Yuming Wang <yumwang@ebay.com>', '-m', u'Closes #213 from wangyum/add-committer.']

Merge complete (local ref PR_TOOL_MERGE_PR_213_ASF-SITE). Push to apache? (y/n): y
git push apache PR_TOOL_MERGE_PR_213_ASF-SITE:asf-site
Username for 'https://github.com': wangyum
Password for 'https://wangyum@github.com':
remote: Permission to apache/spark-website.git denied to wangyum.
fatal: unable to access 'https://github.com/apache/spark-website.git/': The requested URL returned error: 403
Restoring head pointer to asf-site
git checkout asf-site
Checking out files: 100% (3732/3732), done.
Switched to branch 'asf-site'
git branch
Deleting local branch PR_TOOL_MERGE_PR_213
git branch -D PR_TOOL_MERGE_PR_213
Deleting local branch PR_TOOL_MERGE_PR_213_ASF-SITE
git branch -D PR_TOOL_MERGE_PR_213_ASF-SITE
Exception while pushing: Command '[u'git', u'push', u'apache', u'PR_TOOL_MERGE_PR_213_ASF-SITE:asf-site']' returned non-zero exit status 128
Restoring head pointer to asf-site
git checkout asf-site
Already on 'asf-site'
git branch
Restoring head pointer to asf-site
git checkout asf-site
Already on 'asf-site'
git branch
```

```
yumwang@ubuntu-3513086:~/spark-website$ git remote -v
apache	https://github.com/apache/spark-website.git (fetch)
apache	https://github.com/apache/spark-website.git (push)
apache-github	git://github.com/apache/spark-website (fetch)
apache-github	git://github.com/apache/spark-website (push)
origin	https://github.com/wangyum/spark-website.git (fetch)
origin	https://github.com/wangyum/spark-website.git (push)
upstream	https://github.com/apache/spark-website.git (fetch)
upstream	https://github.com/apache/spark-website.git (push)
```

**Comment by gatorsmile** [comment]
Congratulations!

**Comment by srowen** [comment]
Hm, you set up the token as in https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line ?
Maybe try again today or tomorrow in case it took some time to propagate?

**Comment by dongjoon-hyun** [comment]
Hi, @wangyum . So, you have `export GITHUB_OAUTH_KEY=...` in the environment variable, right?
Then, could you try to use `git@github.com:apache/spark-website.git` instead of `https://github.com/apache/spark-website.git`?
```
yumwang@ubuntu-3513086:~/spark-website$ git remote -v
apache	https://github.com/apache/spark-website.git (fetch)
apache	https://github.com/apache/spark-website.git (push)
```

**Review by zhengruifeng — APPROVED** [review]

**Comment by gengliangwang** [comment]
> I setup 2-faced auth and use access token. But it always fails when pushing to remote:
remote: Permission to apache/spark-website.git denied to wangyum.

I got the same issue as @wangyum in #218 . I tried yesterday and still hit it today.
I have tried both `https://github.com/apache/spark-website.git` and `git@github.com:apache/spark-website.git` for the remote `apache`

**Comment by HyukjinKwon** [comment]
@viirya, do you have any idea on that? Did you face similar issue too?

**Comment by viirya** [comment]
No. I don't have this issue. Have you synced your github account with apache?

**Review by viirya — APPROVED** [review]

**Comment by gengliangwang** [comment]
> No. I don't have this issue. Have you synced your github account with apache?

@viirya thanks. I have filled my account in https://id.apache.org/ and joined the organization https://github.com/apache . 

I just did a quick search and found this: https://reference.apache.org/committer/github
Let me try it.

**Comment by viirya** [comment]
Have you tried this https://gitbox.apache.org/setup/?

**Comment by gengliangwang** [comment]
> Have you tried this https://gitbox.apache.org/setup/?

Yes, I just complete it. I will try to merge again after one hour. Thank you.

**Review by gengliangwang — APPROVED** [review]

**Comment by wangyum** [comment]
Thank you @viirya

**Pull request closed without merging**
