### PR TITLE
Update Spark 3.4 release window

### PR DESCRIPTION
**Pull request by xinrong-meng**
This PR proposes to update Spark 3.4 release window.

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
It's fine, it might be a bit optimistic, but can be changed

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you! Actually, I agree with this and tried a similar scheduling in the community. However, I remember that it was always controversial in the community due to the seasonal issue. Since Apache Spark 3.3.0 was released on Jun 16, please initiate a discussion on the mailing list first, @xinrong-meng .  :)

**Comment by xinrong-meng** [comment]
Thanks @dongjoon-hyun! I will initiate the discussion on the mailing list.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
According to the discussion on the dev mailing list, I'll merge this

**Comment by xinrong-meng** [comment]
Thank you @dongjoon-hyun ! :)

**Pull request merged**
