### PR TITLE
Add Haejoon Lee to committers

### PR DESCRIPTION
**Pull request by itholic**
Add Haejoon Lee to committers

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
Congratulations!

**Comment by HeartSaVioR** [comment]
Congrats!

**Comment by HyukjinKwon** [comment]
Merged to asf-site.

**Comment by itholic** [comment]
Thanks @HyukjinKwon and @HeartSaVioR !

**Comment by LuciferYang** [comment]
Congratulations ~

**Pull request closed without merging**
