### PR TITLE
Update committer page

### PR DESCRIPTION
**Pull request by mridulm**
I joined LinkedIn

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Comment by mridulm** [comment]
@srowen I had removed local changes to site/developer-tools.html, site/examples.html, site/security.html, site/sitemap.xml made during to jekyl build before submitting pr - but looks like a merge will regenerate them ...
Is there a way to suppress this ? 

Looks like version changes are triggering bunch of whitespace related mods - which will keep toggling based on which version everyone is on.

I am on 3.8.6 of jekyll (new box, so most deps are new from apt)

**Review by HyukjinKwon — APPROVED** [review]
:)

**Comment by HyukjinKwon** [comment]
@mridulm, yeah they're some differences per the Jekyll version. I tried to make some fixes to minimise the diff before but not sure if we can have a great way to avoid them. I usually do the same thing as you did.

**Review by gengliangwang — APPROVED** [review]

**Comment by srowen** [comment]
I'm on jekyll 4.1.0, and ideally, we'd use the latest one consistently. But yeah I usually revert any spurious changes and don't deal with it

**Comment by mridulm** [comment]
Sounds good, thanks @HyukjinKwon, @srowen ! Merged

**Pull request closed without merging**
