### PR TITLE
Update versioning policy with 2.2.x

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR updates EOL documents with release 2.2.x explicitly.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @maropu .
This might be a better answer for the question you received.

cc @srowen and @HyukjinKwon

**Review by srowen — APPROVED** [review]
That's fine. I don't know if we need to keep updating this example further for 2.3, etc, but this is OK.

**Comment by dongjoon-hyun** [comment]
Thanks, @srowen !

**Comment by maropu** [comment]
Really cool! Thanks, @dongjoon-hyun!

**Comment by HyukjinKwon** [comment]
+1

**Comment by dongjoon-hyun** [comment]
Thanks, @maropu and @HyukjinKwon .

**Pull request merged**
