### PR TITLE
[FOLLOWUP] Add Matomo analytics to the published documents

### PR DESCRIPTION
**Pull request by panbingkun**
The pr is followup https://github.com/apache/spark-website/pull/479, https://github.com/apache/spark/pull/43454, https://github.com/apache/spark-website/pull/485.

The pr aims to add `Matomo analytics` to the `published documents`.

As discussed, we aim to fix the aforementioned issues by directly repairing files that have already been released in history.

include versions: 3.1.2, 3.1.3, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.5.0
PS: `Adding Matomo analytics` to the document in version 3.1.1 has been completed in PR: https://github.com/apache/spark-website/pull/485

### CODE REVIEW

**Comment by panbingkun** [comment]
Through the following URL:
https://analytics.apache.org/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=40#?idSite=40&period=day&date=yesterday&category=General_Actions&subcategory=Actions_SubmenuPagesEntry

We can observe that `the document access statistics for version 3.1.1` can be viewed as follows:
image

In this PR, we have completed versions: `3.1.2, 3.1.3, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.5.0`.

**Comment by panbingkun** [comment]
cc @zhengruifeng @itholic @allisonwang-db @HyukjinKwon @srowen

**Comment by srowen** [comment]
I think it's OK. It's not strictly necessary we go back and add this, but it's OK

**Comment by allisonwang-db** [comment]
@panbingkun this is awesome! Just want to make sure, does it also cover the `/latest/` URLs? These should be covered by the `3.5.0` version right?

**Comment by panbingkun** [comment]
> @panbingkun this is awesome! Just want to make sure, does it also cover the `/latest/` URLs? These should be covered by the `3.5.0` version right?

I found that `latest` is `a soft link` in project `spark-website` to `3.5.0`.
image
So, if we have already updated `3.5.0`, it should also be synchronized and updated.

**Comment by HyukjinKwon** [comment]
Merged to asf-site.

**Pull request closed without merging**
