### PR TITLE
Add docs for Apache Spark 3.3.2

### PR DESCRIPTION
**Pull request by viirya**
Adds docs from https://dist.apache.org/repos/dist/dev/spark/v3.3.2-rc1-docs/

### CODE REVIEW

**Comment by srowen** [comment]
LOL I have no idea how to meaningfully review it, but at least the number of files changed (~3M?!) looks like what happened last time, so OK

**Comment by viirya** [comment]
cc @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
+1, LGTM!

**Comment by viirya** [comment]
I forgot how do we merge pr into spark-website. 😂  Do we use `merge_pr.py` or just click "Squash and merge" button?

**Comment by srowen** [comment]
Use the script

**Comment by viirya** [comment]
Hm, have you seen this:

```
./merge_pr.py
git rev-parse --abbrev-ref HEAD
Which pull request would you like to merge? (e.g. 34): 435

=== Pull Request #435 ===
title   Add docs for Apache Spark 3.3.2
source  viirya/add_doc_3.3.2
target  asf-site
url     https://api.github.com/repos/apache/spark-website/pulls/435

Proceed with merging pull request #435? (y/n): y
git fetch apache-github pull/435/head:PR_TOOL_MERGE_PR_435
fatal: unable to connect to github.com:
github.com[0: 192.30.255.113]: errno=Operation timed out
```

**Comment by srowen** [comment]
Wow no. I suppose you can use the merge button if you have to

**Comment by dongjoon-hyun** [comment]
I used the script to merge this~

```
$ ./merge_pr.py
git rev-parse --abbrev-ref HEAD
Which pull request would you like to merge? (e.g. 34): 435

=== Pull Request #435 ===
title	Add docs for Apache Spark 3.3.2
source	viirya/add_doc_3.3.2
target	asf-site
url	https://api.github.com/repos/apache/spark-website/pulls/435

Proceed with merging pull request #435? (y/n): y
git fetch apache pull/435/head:PR_TOOL_MERGE_PR_435
remote: Enumerating objects: 8903, done.
remote: Counting objects: 100% (8903/8903), done.
remote: Compressing objects: 100% (2274/2274), done.
remote: Total 8899 (delta 6645), reused 8828 (delta 6609), pack-reused 0
Receiving objects: 100% (8899/8899), 36.03 MiB | 16.96 MiB/s, done.
Resolving deltas: 100% (6645/6645), completed with 3 local objects.
From github.com:apache/spark-website
 * [new ref]             refs/pull/435/head -> PR_TOOL_MERGE_PR_435
git fetch apache asf-site:PR_TOOL_MERGE_PR_435_ASF-SITE
From github.com:apache/spark-website
 * [new branch]          asf-site   -> PR_TOOL_MERGE_PR_435_ASF-SITE
git checkout PR_TOOL_MERGE_PR_435_ASF-SITE
Switched to branch 'PR_TOOL_MERGE_PR_435_ASF-SITE'
['git', 'merge', 'PR_TOOL_MERGE_PR_435', '--squash']
Updating files: 100% (8590/8590), done.
['git', 'log', 'HEAD..PR_TOOL_MERGE_PR_435', '--pretty=format:%an <%ae>']
Enter primary author in the format of "name <email>" [Liang-Chi Hsieh <viirya@gmail.com>]:
['git', 'log', 'HEAD..PR_TOOL_MERGE_PR_435', '--pretty=format:%h [%an] %s']
['git', 'commit', '--author="Liang-Chi Hsieh <viirya@gmail.com>"', '-m', 'Add docs for Apache Spark 3.3.2', '-m', 'Adds docs from https://dist.apache.org/repos/dist/dev/spark/v3.3.2-rc1-docs/', '-m', 'Author: Liang-Chi Hsieh <viirya@gmail.com>', '-m', 'Closes #435 from viirya/add_doc_3.3.2.']

Merge complete (local ref PR_TOOL_MERGE_PR_435_ASF-SITE). Push to apache? (y/n): y
git push apache PR_TOOL_MERGE_PR_435_ASF-SITE:asf-site
Enumerating objects: 8903, done.
Counting objects: 100% (8903/8903), done.
Delta compression using up to 10 threads
Compressing objects: 100% (2238/2238), done.
Writing objects: 100% (8899/8899), 36.03 MiB | 6.38 MiB/s, done.
Total 8899 (delta 6645), reused 8898 (delta 6645), pack-reused 0
remote: Resolving deltas: 100% (6645/6645), completed with 3 local objects.
remote: Checking connectivity: 6618, done.
To github.com:apache/spark-website.git
   551848fe0..d11ffbdb6  PR_TOOL_MERGE_PR_435_ASF-SITE -> asf-site
git rev-parse PR_TOOL_MERGE_PR_435_ASF-SITE
Restoring head pointer to asf-site
git checkout asf-site
Switched to branch 'asf-site'
git branch
Deleting local branch PR_TOOL_MERGE_PR_435
git branch -D PR_TOOL_MERGE_PR_435
Deleting local branch PR_TOOL_MERGE_PR_435_ASF-SITE
git branch -D PR_TOOL_MERGE_PR_435_ASF-SITE
Pull request #435 merged!
Merge hash: d11ffbdb
```

**Comment by srowen** [comment]
Although looks like you are hung up just fetching. Fetch asf-site first? See if that works

**Comment by viirya** [comment]
Thanks @dongjoon-hyun !

@srowen I did a separate fetch but got same timeout error.

**Pull request closed without merging**
