### PR TITLE
Add Dongjoon Hyun to the list of committers

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @srowen and @HyukjinKwon .
Could you review this PR?

**Review by HyukjinKwon — APPROVED** [review]
Wow!

**Comment by dongjoon-hyun** [comment]
Thanks. I'll update the title and commit message.

**Review by srowen — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen !

**Comment by dongjoon-hyun** [comment]
Thank you. This is merged to `asf-site` branch by using `merge_pr.py`.

**Pull request closed without merging**
