### PR TITLE
Spark 2.2.2 docs

### PR DESCRIPTION
**Pull request by tgravescs**
I did the jekyll build command but this is the first time I've done it, so please double check as I'm not exactly sure what to look for from that.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by tgravescs** [comment]
merged

**Comment by tgravescs** [comment]
this still isn't showing up in the apache/spark-website github, anyone know how long that takes to propogate?  its been 2 hours:
https://git-wip-us.apache.org/repos/asf?p=spark-website.git;a=shortlog;h=refs/heads/asf-site

**Comment by HyukjinKwon** [comment]
It doesn't usually take so much time given my observation so far. Mind if I try again to merge this one?

**Comment by HyukjinKwon** [comment]
Ah, it's merged okay but it doesn't show up in the commit ... I tried and I can't. Seems there's a problem in github or somewhere.

**Comment by felixcheung** [comment]
I see the commit on https://git-wip-us.apache.org/repos/asf?p=spark-website.git;a=shortlog;h=refs/heads/asf-site but not in github.com - we should open a INFRA ticket?

**Comment by holdenk** [comment]
Oh yeah maybe, for what its worth I saw a sync delay recently as well with the 2.1.3 docs, fixed its self in about a day though that time.

**Comment by tgravescs** [comment]
hmm doesn't seem to have sync'd still, anyone know how this is setup or who to contact?

**Comment by tgravescs** [comment]
ok pushed an empty commit and then it synced

**Pull request closed without merging**
