### PR TITLE
Add Apache Spark 3.4.3 news

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
Vote Result: https://lists.apache.org/thread/3y4p28s1qf4tgkgs45j4ho2z3xrqkqfm
Documentation: https://spark.apache.org/docs/3.4.3/
Binary: https://downloads.apache.org/spark/spark-3.4.3/
PySpark: https://pypi.org/project/pyspark/3.4.3/
Maven Central: https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.13/3.4.3/

**SCREENSHOTS**

Screenshot 2024-04-18 at 08 51 38

Screenshot 2024-04-18 at 08 52 31

Screenshot 2024-04-18 at 08 53 18

Screenshot 2024-04-18 at 08 54 09

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this PR too, @viirya ?

**Comment by dongjoon-hyun** [comment]
Could you review this `News` PR, @huaxingao ?

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya !

**Review by huaxingao — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @huaxingao , too!

**Pull request closed without merging**
