### PR TITLE
Document the signals for Hive 1.2 and 2.3 profiles

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This PR documents the signals for Hive 1.2 and 2.3 profiles

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @gatorsmile, @dongjoon-hyun, @wangyum

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Thanks @srowen.

**Comment by dongjoon-hyun** [comment]
+1, late LGTM. It was all time record. (6 minutes!). 😄

**Comment by maropu** [comment]
oh, the fast merging.

**Review by gatorsmile — COMMENTED** [review]
Thank you! @HyukjinKwon

**Pull request closed without merging**
