### PR TITLE
Add 404 page with instuctions for EOL docs

### PR DESCRIPTION
**Pull request by yaooqinn**
# Before
image

# After

image

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by yaooqinn** [comment]
Merged to asf-site. Thank you @HyukjinKwon

**Comment by yaooqinn** [comment]
Excuse me for committing [a followup](https://github.com/apache/spark-website/commit/dfba8b85b7d7a66b775c9bfff20211acee5ea88b) w/o review. This patch is required by [Apache Web Servers](https://jekyllrb.com/tutorials/custom-404-page/#hosting-on-apache-web-servers). And I needed to test via the Apache server w/ the patch deployed.


The 404 now works both online and on localhost

FYI, https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.sql.DataFrame.dropDuplicates.html

**Review by dongjoon-hyun — COMMENTED** [review]
+1, late LGTM. Thank you!

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun

**Comment by allisonwang-db** [comment]
Thanks for adding this! This looks much better.

**Pull request merged**
