### PR TITLE
Add Peter Toth to committers

### PR DESCRIPTION
**Pull request by peter-toth**

### CODE REVIEW

**Comment by peter-toth** [comment]
cc @HyukjinKwon

**Review by mridulm — APPROVED** [review]
Congratulations!

**Review by wangyum — APPROVED** [review]
Congrats!

**Comment by HeartSaVioR** [comment]
Finally! Congrats!

**Comment by HeartSaVioR** [comment]
@peter-toth Use this PR as testing your committership.

**Review by ulysses-you — APPROVED** [review]
Congrats!

**Review by HyukjinKwon — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]
Congrats!

**Comment by roryqi** [comment]
Congrats! Deeply admire your significant contributions to the Apache Spark.

**Comment by peter-toth** [comment]
Thank you @mridulm, @wangyum, @HeartSaVioR, @ulysses-you, @HyukjinKwon, @yaooqinn, @jerqi!

**Comment by dongjoon-hyun** [comment]
Congrats, @peter-toth !

**Comment by peter-toth** [comment]
Thank you @dongjoon-hyun!

**Comment by zhengruifeng** [comment]
Late LGTM, Congrats!

**Comment by peter-toth** [comment]
Thanks @zhengruifeng!

**Pull request closed without merging**
