### PR TITLE
Update release-process.md

### PR DESCRIPTION
**Pull request by wangyum**
This pr updates `release-process.md` because it is outdated.

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Review by maropu — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by wangyum** [comment]
@HyukjinKwon Could you help make `merge_pr.py` support python3?
```
yumwang@ubuntu-3513086:~/spark-website$ ./merge_pr.py
Traceback (most recent call last):
  File "./merge_pr.py", line 31, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2
```

**Comment by HyukjinKwon** [comment]
No, we should fix it to support.

**Comment by HyukjinKwon** [comment]
Merged.

**Comment by HyukjinKwon** [comment]
Will take a look later.

**Pull request closed without merging**
