### PR TITLE
Fix remotes URLs to point to apache/spark

### PR DESCRIPTION
**Pull request by zero323**
How to Merge a Pull Request section describes process of working with main Spark
repositiory. However, `git remote` links in the How to Merge a Pull Request point to apache/spark-website.

### CODE REVIEW

**Comment by srowen** [comment]
Oops, right. Can you generate the HTML too? (or simply edit the HTML files too, as this is so simple)

**Comment by zero323** [comment]
> Can you generate the HTML too? (or simply edit the HTML files too, as this is so simple)

Sorry, it slipped my mind. Done.

**Review by srowen — APPROVED** [review]

**Comment by zero323** [comment]
Thanks @srowen!

**Review by HyukjinKwon — COMMENTED** [review]
lgtm2!

**Pull request closed without merging**
