### PR TITLE
Fix signature description broken in PySpark API documentation in 2.2.1

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This PR proposes to fix signature description broken in PySpark API documentation in 2.2.1. See SPARK-24530.

Sphinx version was intentionally matched to reduce the diff.

### CODE REVIEW

**Comment by mengxr** [comment]
Ditto on splitting version changes and ML doc fixes.

**Comment by HyukjinKwon** [comment]
Eh, actually, I followed release process to generate the doc to generate these .. Seems `RELEASE_VERSION` was not set in this previous release when generating the API documentation. It needs some manual efforts to make it separate. Mind if I keep them here please?

**Comment by mengxr** [comment]
sg

**Comment by HyukjinKwon** [comment]
sg maybe stands for "sounds good" but it's also for Singapore where I currently live .. sorry for a bad joke.

Will push this in.

**Pull request closed without merging**
