### PR TITLE
Add geni to third party projects

### PR DESCRIPTION
**Pull request by anthony-khong**
I've tested it with `jekyll build` and `jekyll serve`. It works as expected.

### CODE REVIEW

**Comment by srowen** [comment]
You'll need to use jekyll to regenerate the HTML file from this too

**Review by HyukjinKwon — APPROVED** [review]

**Comment by anthony-khong** [comment]
Hi @srowen, thank you for the tip. When I ran `jekyll` I got a lot of changes in the files below. Not sure why, but as I understand it, I only need the only line of the HTML. Hope that's okay!

```
$ git diff
        modified:   site/committers.html
        modified:   site/community.html
        modified:   site/contributing.html
        modified:   site/developer-tools.html
        modified:   site/downloads.html
        modified:   site/examples.html
        modified:   site/mailing-lists.html
        modified:   site/news/index.html
        modified:   site/powered-by.html
        modified:   site/release-process.html
        modified:   site/releases/spark-release-0-8-0.html
        modified:   site/releases/spark-release-0-8-1.html
        modified:   site/releases/spark-release-0-9-0.html
        modified:   site/releases/spark-release-1-0-0.html
        modified:   site/releases/spark-release-1-0-1.html
        modified:   site/releases/spark-release-1-1-0.html
        modified:   site/releases/spark-release-1-2-0.html
        modified:   site/releases/spark-release-1-2-2.html
        modified:   site/releases/spark-release-1-3-0.html
        modified:   site/releases/spark-release-1-5-0.html
        modified:   site/releases/spark-release-1-6-0.html
        modified:   site/releases/spark-release-2-1-0.html
        modified:   site/releases/spark-release-2-2-0.html
        modified:   site/releases/spark-release-2-2-1.html
        modified:   site/releases/spark-release-2-3-0.html
        modified:   site/releases/spark-release-2-3-1.html
        modified:   site/releases/spark-release-2-4-0.html
        modified:   site/releases/spark-release-2-4-1.html
        modified:   site/releases/spark-release-2-4-2.html
        modified:   site/releases/spark-release-3-0-0.html
        modified:   site/screencasts/index.html
        modified:   site/security.html
        modified:   site/sitemap.xml
        modified:   site/third-party-projects.html
        modified:   site/versioning-policy.html
```

**Comment by HyukjinKwon** [comment]
Yeah, the output differs per the Jekyll version. Exclude other changes. That's what I usually do too.

**Comment by srowen** [comment]
Yeah it _shouldn't_ be too different if you use a recent jekyll but who knows. Just revert the rest. You can honestly probably create the change to the HTML by hand too by copying and pasting.

**Review by srowen — APPROVED** [review]

**Pull request closed without merging**
