### PR TITLE
Added Data Pipelines to Powered By page

### PR DESCRIPTION
**Pull request by roland1982**

### CODE REVIEW

**Comment by roland1982** [comment]
HTML change:

- <a href="https://datapipelines.com">Data Pipelines</a>
  - Build and schedule ETL pipelines step-by-step via a simple no-code UI.

**Comment by maropu** [comment]
Please generate a html page via `Jekyll`, e.g., https://github.com/apache/spark-website/pull/268

**Comment by maropu** [comment]
cc: @srowen

**Comment by roland1982** [comment]
@maropu done

**Comment by maropu** [comment]
Thanks! Merged to `asf-site` (Note that I checked the request in dev mailing list: http://apache-spark-developers-list.1001551.n3.nabble.com/Companies-and-Organizations-listing-for-datapipelines-com-td29511.html)

**Pull request closed without merging**
