### PR TITLE
Add Spark 2.2.3 docs

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR aims to add only the voted Apache Spark 2.2.3 `docs` directory. In the followup PR, I'll update the others (the links and announce and committer guide update items like https://checker.apache.org/projs/spark.html)

```
site/docs/2.2.3
```

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @srowen , @felixcheung , @dbtsai ?

**Review by srowen — APPROVED** [review]
Heh, it's pretty hard to actually review, but seems similar in size to https://github.com/apache/spark-website/commit/52917ac46ab620027d7c04c8c0e2cf6be4be8df0 and skimming some files, it looks OK.

**Comment by felixcheung** [comment]
yeah, it's hard to review. if you could double check only site/ is changing then it should be ok

**Review by felixcheung — APPROVED** [review]

**Comment by felixcheung** [comment]
I did a quick check after merging, looks good

**Comment by srowen** [comment]
@dongjoon-hyun there's a separate change to add a news item and the download link to come right?

**Comment by dongjoon-hyun** [comment]
Thank you, @felixcheung and @srowen .
Yes. Right, @srowen . I'm working on them~

**Pull request merged**
