### PR TITLE
Add Maciej Szymkiewicz to committers

### PR DESCRIPTION
**Pull request by zero323**

### CODE REVIEW

**Review by HeartSaVioR — APPROVED** [review]
Congrats!

**Review by HyukjinKwon — APPROVED** [review]
Congrats @zero323!

**Review by maropu — APPROVED** [review]
Congrats, @zero323 !

**Comment by yaooqinn** [comment]
Congrats!

**Comment by huaxingao** [comment]
@zero323 Congratulations!!

**Review by huaxingao — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Comment by zero323** [comment]
Thanks everyone!

**Comment by zhengruifeng** [comment]
Congrats!

**Pull request closed without merging**
