### PR TITLE
Don't include preview versions in `Release Notes for Stable Releases`

### PR DESCRIPTION
**Pull request by jiangxb1987**
We should not include preview versions in the `Release Notes for Stable Releases` of the downloads page, this PR add a filter to resolve the issue.

Other changes are auto generated from running `jekyll build` locally.

### CODE REVIEW

**Comment by jiangxb1987** [comment]
cc @srowen @HyukjinKwon @dongjoon-hyun @gatorsmile

**Comment by kiszk** [comment]
Looks good in changes `downloads.js`. Do we need to update html files, too?

**Comment by jiangxb1987** [comment]
I'm not sure, those changes are auto generated  from running `jekyll build` locally.

**Review by HyukjinKwon — APPROVED** [review]
Looks good if it works.

**Comment by kiszk** [comment]
I see. [The same thing](https://github.com/apache/spark-website/commit/19eaa8177be8141b95384311e75824a1062e91b4#diff-25ff43f1cd3eb127660998d843ddbf85) occured before.

**Review by kiszk — APPROVED** [review]

**Comment by srowen** [comment]
Hm, don't we have to update the markdown? or is this a problem with auto-generated HTML?

**Review by srowen — APPROVED** [review]
OK if I understand correctly the rest of the HTML changes are from updates to jekyll or something.

**Comment by jiangxb1987** [comment]
Thanks @srowen @kiszk @HyukjinKwon !

**Pull request closed without merging**
