### PR TITLE
Added the Spark Operator as a third-party project

### PR DESCRIPTION
**Pull request by liyinan926**
@srowen.

### CODE REVIEW

**Comment by srowen** [comment]
@liyinan926 actually I believe the PMC would say that project names like "Spark Operator" aren't allowed under ASF trademark guidelines. Could the description be changed to rename it "K8S Operator for Apache Spark" or similar?

**Comment by liyinan926** [comment]
@srowen the description has been fixed.

**Comment by srowen** [comment]
It looks like you still need to regenerate the HTML. The project site still says Spark Operator too. The project name would need to be something like 'Operator for Apache Spark'

**Comment by liyinan926** [comment]
Oops, forgot to rebuild. Fixed now.

**Comment by srowen** [comment]
I am talking about https://github.com/GoogleCloudPlatform/spark-on-k8s-operator , and still don't see updates there.

**Comment by liyinan926** [comment]
You meant the name of the repo `spark-on-k8s-operator` or the appearances of the term `Spark Operator` in project description and documentation?

**Comment by srowen** [comment]
See https://spark.apache.org/trademarks.html Generally there's an exception for software identifiers like a repo or artifact or package name string. But yes I am otherwise talking about how the project is titled. 'Spark Operator' would not be consistent with these guidelines.

**Comment by liyinan926** [comment]
Thanks for the info. Will rename it to `K8S Operator for Apache Spark` in the documentation. So the repo name is fine, right?

**Comment by srowen** [comment]
Yes, although ideally projects just choose a name without Spark at all and therefore don't need it in package or repo IDs, for those that do, it's recognized that using a long ID with '-for-apache-spark' is cumbersome.

**Comment by liyinan926** [comment]
The project documentation has been fixed to use `Kubernetes Operator for Apache Spark` instead of `Spark Operator`.

**Review by srowen — APPROVED** [review]

**Pull request closed without merging**
