### PR TITLE
Fix confict warning on spark-summit-east-agenda-posted

### PR DESCRIPTION
**Pull request by Yikun**
When use `bundle exec jekyll build` to generate the htmls, the below error is raised:
```
Conflict: The following destination is shared by multiple files.
The written file may end up with unexpected contents.
/Users/jiangyikun/spark/spark-website/site/news/spark-summit-east-agenda-posted.html
 - spark-website/news/_posts/2015-01-21-spark-summit-east-agenda-posted.md
 - spark-website/news/_posts/2016-01-14-spark-summit-east-agenda-posted.md
```
The reason is there were two files have same url suffix:
- 2015-01-21-spark-summit-east-agenda-posted
- 2016-01-14-spark-summit-east-agenda-posted

And there ware only one page is generated, the content is overwriten by the
page with 2016-01-14 date prefix, and the 2015-01-21 one is lost. See [1].

This patch adds year suffix to fix this confict issue.

[1] http://spark.apache.org/news/spark-summit-east-agenda-posted.html

### CODE REVIEW

**Comment by srowen** [comment]
That should be fine yes. I think we now generate with "bundle exec jekyll build" - it probably results in the same output if you use jekyll 4.2.0 but just checking. (And our new linter job here might check that for us)

**Comment by Yikun** [comment]
@srowen Actually, the error is output from `bundle exec jekyll build`, you could have a try, and the commit msg was just shortening cmd, 

~emm, I should write complete cmd in there.~ done

And looks like we should also change this cmd in  https://github.com/apache/spark-website/blame/asf-site/.github/PULL_REQUEST_TEMPLATE.md#L1. : ) 

Added: https://github.com/apache/spark-website/pull/315

**Comment by HyukjinKwon** [comment]
cc @attilapiros FYI

**Comment by attilapiros** [comment]
Thanks for fixing this! 

I have not realized this bug as I was really focused on picking up the right version of Jekyll.

**Comment by attilapiros** [comment]
@srowen  @HyukjinKwon  what about extending the github workflow action by checking the stderr of the generation is empty?

**Comment by HyukjinKwon** [comment]
Yeah sounds good

**Review by attilapiros — APPROVED** [review]
LGTM

**Pull request closed without merging**
