### PR TITLE
replace `docs/latest/">Latest Release (Spark 3.3.2)`

### PR DESCRIPTION
**Pull request by bjornjorgensen**
This is for replacing the rest for `Latest Release (Spark 3.3.2)` to `Latest Release`
replace docs/latest/">Latest Release (Spark 3.3.2) -> docs/latest/">Latest Release

This is a followup on https://github.com/apache/spark-website/pull/439

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Got it.  BTW, why didn't you generate this in the previous PR, @bjornjorgensen ?

**Comment by bjornjorgensen** [comment]
The last was for one `Latest Release (Spark 3.3.1)` to `Latest Release (Spark 3.3.2)` 
Then after the vote I asked if it was ok with the one.. and it was just merged.

**Review by viirya — COMMENTED** [review]
Hm? I think this is correct and they are generated by `jekyll`.

**Comment by bjornjorgensen** [comment]
Find and replace in vs code

**Comment by dongjoon-hyun** [comment]
Got it, but you should not do like that, @bjornjorgensen .
> Find and replace in vs code

**Review by dongjoon-hyun — COMMENTED** [review]
Please make it sure that you generated this as @viirya mentioned.

**Comment by bjornjorgensen** [comment]
OK, new PR so I close this one. 
Thanks.

**Pull request closed without merging**
