### PR TITLE
Add Matomo analytics to the published documents

### PR DESCRIPTION
**Pull request by panbingkun**
The pr is followup https://github.com/apache/spark-website/pull/479 and https://github.com/apache/spark/pull/43454

The pr aims to add `Matomo analytics` to the `published documents`.

As discussed, we aim to fix the aforementioned issues by directly repairing files that have already been released in history.

include versions: 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.5.0

### CODE REVIEW

**Comment by panbingkun** [comment]
At present, this PR has only made changes to the historical document of version `3.1.1`. If there are no issues with similar modifications, I will use tools to make similar modifications to other versions.

PS: This PR will involve a lot of files.

**Comment by panbingkun** [comment]
cc @zhengruifeng @itholic @allisonwang-db @HyukjinKwon @srowen

**Review by HyukjinKwon — APPROVED** [review]
This is really nice!

**Review by itholic — APPROVED** [review]
Thanks!

**Comment by allisonwang-db** [comment]
This is awesome! Thanks for adding it to ALL API docs! Let's see if it works for 3.1.1.

**Review by yaooqinn — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to asf-site.

**Pull request closed without merging**
