### PR TITLE
Add R code style guide

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This PR proposes to document R code styles. The contents are basically based on [SPARK-6813](https://issues.apache.org/jira/browse/SPARK-6813).

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @srowen, @shivaram and @felixcheung, I remember I suggested this in  https://github.com/apache/spark/pull/14705#issuecomment-240916602 and I assume we want this.

The contents are based on SPARK-6813. It seems the current lintr emits an error for dot in variable names as observed before - https://github.com/apache/spark/pull/17178#issuecomment-286366193

This seems actually against https://google.github.io/styleguide/Rguide.xml#identifiers. I am going to submit a PR to disable [multiple_dots_linter](https://github.com/jimhester/lintr/blob/master/R/deprecated.R#L78-L91) which I believe causes the error after this gets merged.

**Comment by JohnGetHub** [comment]
???

**Comment by HyukjinKwon** [comment]
@JohnGetHub could you elaborate if I did something wrong or misunderstood?

**Comment by JohnGetHub** [comment]
no,open a joke

**Comment by felixcheung** [comment]
Thanks looks fine, I'd imagine we could add more details on naming, including one-dot, two-dot or multiple dot. But that could come later.

**Pull request merged**
