### PR TITLE
:) bogotá-meetup

### PR DESCRIPTION
**Pull request by megelon**
Hello

I am Co-organizer of Apache Spark Bogotá Meetup from Colombia
https://www.meetup.com/es/Apache-Spark-Bogota/

And would like to include the community on the following web page.

https://spark.apache.org/community.html

Looking forward to meeting you

### CODE REVIEW

**Comment by srowen** [comment]
You need to regenerate the site HTML too - there are instructions in the README

**Comment by megelon** [comment]
Tks for the patience. :rocket:

**Comment by srowen** [comment]
Ah looks like you have an older version of jekyll maybe. It generated lots of other changes. Can you revert everything except your new link in the .md and .html file?

**Comment by megelon** [comment]
I have jerkyll 4.1.1 :sweat_smile: 

I revert everything except the community.md and the site/community.html 

But doesn't look's good will try again, sorry.

**Comment by srowen** [comment]
Oh OK, it may even be the other way around. Anyway, yeah just revert all the changes except the one you are intending.

**Comment by megelon** [comment]
No problem. I am closing this PR and starting a cleaner one. :grimacing:

**Comment by megelon** [comment]
:hand: I am pushing the new branch but recieved this message :sweat_smile: 

ERROR: Permission to apache/spark-website.git denied to megelon.

Can you help me? Please

**Comment by srowen** [comment]
You would have to push to your branch in your fork, not the main one. Make sure you made a branch against your fork?

**Pull request closed without merging**
