### PR TITLE
Spark pride

### PR DESCRIPTION
**Pull request by holdenk**
Change to the Spark Pride logo as discussed. Once finished we can git mv the -back files over it until we want to swap in a special logo again. Also adds spark-logo-pride.png & xcf for permalinks.
result

### CODE REVIEW

**Comment by holdenk** [comment]
I need to cut out the one logo which folks liked.

**Comment by holdenk** [comment]
Note: this does not rebuild the documentation since we normally consider that tied to a release I figured that probably better not to change that logo but open to doing that if that's what folks think is the right path.

**Comment by askerqa** [comment]
Is it legal in ASF? We should be neutral; lgbtq logo is not neutral. ASF Code of Conduct says that everyone is welcome, so any ideological post may break this rule (as somebody may be feeling it's agains someone, i.e. person with orientation that do not use  to lgbtq logo may feels that is not welcome). No other project makes such change. For sure there will be complaints that community should be neutral and do not support one more than others. My 50 cents from no name ;) Don't feel bad for this, it's only a question with personal opinion

**Comment by holdenk** [comment]
@askerqa It's been cleared with trademarks@ and the PMC was only +1s or lack of response (e.g. lazy consensus). Recently the Scala project made a collection of pride logos (although that's on stickers and t-shirts not their website currently), and many tech employers also make similar changes to their websites for pride month (as well as other companies). It's true though I don't know of other ASF projects creating pride variants of their logo (although certainly they do make special variants of their logos for other occasions).

**Comment by holdenk** [comment]
cc @vanzin

**Comment by koeninger** [comment]
+1 to this, I think it's in line with the ASF diversity statement.

**Comment by askerqa** [comment]
Could you please check it? If it breaks neutrality it IMHO breaks Code of Conduct. I don't want to have some problems for Spark, it's not only PMCs :) I know some companies are changing logos, but we should stick to neutrality and not supporting ones more than others. Very bad that PMCs did't ask the community first

**Comment by koeninger** [comment]
@askerqa I don't see the word "neutral" anywhere on https://www.apache.org/foundation/policies/conduct.html

I do see "we explicitly honour diversity in: ...gender identity or expression.... sexual orientation"

**Comment by askerqa** [comment]
"We are committed to being a community that everyone feels good about joining."

And
"No matter how you identify yourself or how others perceive you: we welcome you. Though no list can hope to be comprehensive, we explicitly honour diversity in:"

Non-lgbtq supported may not feel welcome by lgbtq logo. "Honoure" doesn't mean "we allow to make any ideological moves", it means that you still may contribute no matter what i.e. orientation you have. Others with orientations that are not listed by lgbtq may feel bad. Also, ASF never makes such changes

**Comment by jbdeboer** [comment]
@askerqa If you want to talk about this line of reasoning offline (recommended), I am happy to chat on the phone or video. Please email me at james@huronbox.com to set up a time. If you are in California or nearby, I'm happy to meet you in person.

Until then, and until you have a deeper understanding around gender identity, please sit this conversation out. Your comments here start from a deeply flawed premise and, as currently written, are quite hurtful. 

I know that you don't mean to hurt people and I am sure you have a lot to offer this community. Please reach out, we have a lot to talk about. Until then, removing all your comments from this thread is a good immediate step towards betterment.

**Comment by askerqa** [comment]
I don't want to hurt anyone. But will person with identity other than lgbtq (who says there are much more identities) feel ok that is missed? 

Why whole community weren't asked? 

What about Muslims and Jews, they are typically against lgbtq as you maybe know (not all, but most of them especially in Asia). You realy want to hurt my Muslim friends?! They will be very sad that they are not welcome, you know that most of Muslims will feel bad about this.

Yeah, I will stop posting now if questions about others than lgbtq are considered to be harmful. I just don't want to hurt anyone and neutrality is the best option. Sorry if you got my questions wrong! 

BTW I won't delete my posts yet. Legal questions imho should be answered. I feel quite opressed that you try to censorship my questions, it's very unwelcoming. As said this logo hurts a lot of people and we should think about them. I have a good understanding of gender identity, but also about others traditions like Muslims.

**Comment by srowen** [comment]
@jbdeboer I think that @askerqa is raising a legitimate question in good faith and do not think this person needs to be told to 'sit out'. This is unnecessarily dismissive when one should be able to advance simple arguments about why it is not a problem. 

I understand the 'pride' movement as pro-diversity more than anything, and that is a value that the ASF supports and is not neutral on. I do not see it as promoting a group unfairly or at the expense of others in practice even if one might read it that way in theory. 

I can even understand someone saying they have specific and strong feelings about gender issues and don't like this and that is OK, but, not a view that the ASF is constructed to accommodate. 

Or: I'd defer to the apparent significant support for this amongst others who also have considered this in good faith. 

Or: this really isn't a big deal nor the hill to die on?

**Comment by koeninger** [comment]
Any legitimate legal question was already answered when Holden said it had been cleared with trademarks@ and the PMC.

**Comment by MLnick** [comment]
As mentioned above this has been cleared by both ASF trademarks and Spark PMC. LGTM!

**Comment by askerqa** [comment]
It wasn't cleared. It has nothing about trademarks, but about Code of Conduct. 

"community that everyone feels good about joining." and "No matter how you identify yourself or how others perceive you: we welcome you. "

And now tell, how Muslims or people with other identity than lgbtq may feel? Muslims are typically against lgbtq, but they are not telling it everywhere here to not break CoC. You want to just say, that my friends are less valuable? I don't understand. If we support in one case one group, almost always other group will feel bad about this. Did you change logo for Christmas, Ramadan? I didn't notice. 

If we want to be really welcoming, we should avoid situation when one group is more supported than the other. Come to Paris and tell my friend that well, it's against their rules, but he may feel bad, it's ok for Spark PMCs to say "Muslims may feel bad and we will do nothing". Is this welcoming, is this "feeling good"?

Thanks @srowen for believing in my good intentions. I just want to say: support all equally (and change logo for Christmas, Ramadan, important world-wide events) or not in all cases. In any other cases, always some group will feel bad and this IMHO is against Code of Conduct.

**Comment by srowen** [comment]
It was put to the PMC before this and there were no objections. It was cleared in that sense.

I think you assume that celebrating one group means alienating others and I just don't agree that this is how it plays. Why celebrate at all? Because the group in question is not a majority within the community and it probably helps more than hurts anything to give a special note. 

Would we do the same for Christmas? I think it could be fine. If people aren't as eager to, I suppose it's because there is less perceived barrier to making Christmas-celebrators feel welcome, and because there is a difference between choosing to be part of a group that believes or celebrates something, and having a gender identity that is much less of a choice. 

Certainly a policy that prioritizes making all people feel welcome necessarily un-welcomes people who will object to working with people of certain genders for example. Yes, if the pride logo offends someone who can't work with a gay person, yes, they are correctly getting a message that this belief or behavior isn't welcome here. That is by design. 

BTW I would disagree with your very broad characterization that "Muslims don't like LGBTQ people". I'd bet the vast majority don't hold this view or are perfectly capable of keeping that view out of professional interactions. To suggest this group will generally take offense to a simple logo is, IMHO, pretty damning. Careful!

**Comment by squito** [comment]
+1 on the change, thanks for taking the initiative on this @holdenk !

and though I do not agree with @askerqa , I also think they should not be told to "sit out".

FWIW, I'm muslim and I'm fine with this, though I also think you right, my views dont' represent all muslims and some particular subgroups won't like it.  But I don't think that being inclusive means catering to people that want to *exclude* others.

**Comment by askerqa** [comment]
@squito That's why I posted "most of". Almost all my muslim friends feels uncomfortable with this logo. They say it's against their religion, I'm not a muslim to say why exactly. Also Jews are not comfortable, of course those who I know, I can't say "every Jew".  Personally I have nothing about this - I'm not "let's do it!" and not "Never do this!", but it's about community, so **everyone**

> "Certainly a policy that prioritizes making all people feel welcome necessarily un-welcomes people who will object to working with people of certain genders for example. Yes, if the pride logo offends someone who can't work with a gay person, yes, they are correctly getting a message that this belief or behavior isn't welcome here. That is by design."

Well, they are not posting anything against lgbtq, because they are aware of the rules. They are working with such person, but "gold rule" is that nobody starts this topic to not hurt anyone else. Even if they feel it's not good. I can't judge them - I only work with them, so don't blame me for their opinions. However, community should avoid making **anyone** uncomfortable and unwelcoming, as CoC says. It's very easy to not make them un-welcoming and lgbtq won't be opressed, because no other holidays/special days are celebrated, so we won't threat them in special way. 

My friends stick the rules - and are not posting anything against lgbtq - so you should also do this. In other way it's very unfair and unacceptable to discriminate anyone even if you personally don't accept their point of view. I don't understand them, as catholic I don't feel "opressed" by this logo, but, well, saying that some people are not welcome in the community even if they stick the rules is very, very bad.  

Really, is this topic so important, that you **must** put this logo, even if someone will feel unhappy and uncomfortable? I think lgbtq people like Holden are not discriminated in IT, especially in Spark or any other ASF Community. I've never seen any discriminating posts, so is it really so important to say "all community is with them"? Most of community is with them, but I don't feel that such manifestation are really needed on technical page with represents many nations, religions and genders.

**Comment by holdenk** [comment]
In all seriousness if you (@askerqa )do believe this is a CoC issue there is a procedure mentioned in that for bringing it to a resolution. I know filing CoC reports can be scary, but I’m pretty sure you could do it anonymously as you have with the GitHub interactions.

That being said if there are no objections from folks with votes with merging this as is I’m down to do the merge this morning (I can of course also wait for someone else to merge if that would be better).

**Comment by askerqa** [comment]
@srowen @holdenk I think I found a "work around". Maybe someone with Twitter admin of Spark account will post that "Spark community is friendly to everyone - no matter which gender you have, what religion, what nation. We promote this rule everyday, also remembering about pride month".

Why it's better? It won't be any place to interpret it. It's literally "we are welcoming everyone", not "promote", not "we support in special way", like my friends are interpreting this logo. No one should be offended, because "welcoming" is a key point of ASF. 

WDYT? Just no place for interpretation, literally say what is acceptable in CoC. Everyone that uses Spark should have accepted CoC before, so they can't say it's something they are against (they already accepted it).

**Comment by vanzin** [comment]
For what it's worth, another +1 from a PMC member. Nothing really to add to Sean's messages.

**Comment by hvanhovell** [comment]
FWIW +1 from my end

**Comment by srowen** [comment]
@askerqa your proposal seems to reiterate the ASF position. Again, I believe you are misunderstanding this as promoting a gender identity. Of course it isn't. It is merely specially acknowledging a group that isn't exactly always made to feel welcome (see this thread as evidence) as welcome as much as anyone else.

It doesn't mean all behavior or viewpoints are welcome; specifically, behavior or views that denigrate another group aren't welcome. You are proposing a particular action - silence about whether certain gender identities are OK - that seems to contravene the CoC. We can't forbid this to cater to beliefs that require certain exclusion. It isn't symmetric, and I do assert that your co-workers behaviors are unwelcome here. Accommodating them would violate the CoC. I actually don't understand your argument.

**Comment by askerqa** [comment]
@srowen We should never say that anyone is not welcome in community, it's stricly against CoC, sorry. It has been written directly in the document.

My friends are feeling this to be bad, but that is their opinion. They don't force Spark PMC to say that lgbtq is wrong. But in the meantime Spark PMCs are telling that all community supports lgbtq and muslims are bad if they stick to their religions' rules. It's a dicrimination, even if you say that you are sure it does not break CoC, it's a discrimination. **They may have their opinions, as far as they are not breaking the community it doesn't matter what their opinion is. But, if you raise an idea that hurts someone, don't expect that people won't be quiet.**

Imagine: they don't post that lgbtq is wrong, yes? They are silent to not break CoC and work together with lgbtq people. And you want to post that they are not welcome, because of their opinions that they never before wrote anywhere. They just feel uncomfortable and bad about this new sugestion that they are forced to support lgbtq. They are tolerant (they won't wrote anything bad), but they don't accept lgbtq. 

Not posting anything on the site is not a  discrimination. Every other group is also not listed, so where is the discrimination? 

From this discussion I have one sad news: Spark community is intollerant to other religions. Explicitily. They won't post their opinions, because they are tollerant and know that it may hurt lgbtq and break CoC, but you don't mind that someone will be hurt because of direct support for lgbtq. That is very very sad. Please, imagine for one moment that you are born in other country and have different point of view. 

I've proposed a work-around to support lgbtq and not hurt anyone else. Going in direct support direction is a un-friendly choice, especially that there was no poll, etc., to ask community, not only PMC members.

Personally - I don't matter. But now PMC stuff just wants to say that big group of users are not welcome in the community (even if they will never hurt anyone, just keep opinions in their minds) and is intollerant to other religions and don't understand, that someone else may have other point of view. **Until they explicitly breaks the rules and wrote something bad, interrupt your work, their opinons and rules are not bad for community - it is invisible to the community. Now it becomes visible only because you want to make a move that makes them feel they are less valuable.**

**Comment by vanzin** [comment]
Merging. Thanks Holden!

**Comment by tovbinm** [comment]
Ha ha ;)) This is cool!!

**Comment by aarondav** [comment]
Independent of one's ideological beliefs, I think we can all agree rainbows are cool!

**Pull request closed without merging**
