### PR TITLE
[SPARK-49181] Remove site/docs/{version}/api/python/_sources folders and util/build-error-docs.py

### PR DESCRIPTION
**Pull request by yaooqinn**
This PR removes interim data under the _sources folder for each version listed below:

```
./site/docs/4.0.0-preview1/api/python/_sources
./site/docs/3.1.2/api/python/_sources
./site/docs/3.3.1/api/python/_sources
./site/docs/3.3.0/api/python/_sources
./site/docs/3.1.3/api/python/_sources
./site/docs/3.4.0/api/python/_sources
./site/docs/3.2.2/api/python/_sources
./site/docs/3.4.1/api/python/_sources
./site/docs/3.2.4/api/python/_sources
./site/docs/3.2.3/api/python/_sources
./site/docs/3.5.0/api/python/_sources
./site/docs/3.1.1/api/python/_sources
./site/docs/3.3.2/api/python/_sources
./site/docs/3.5.1/api/python/_sources
./site/docs/3.3.3/api/python/_sources
./site/docs/3.3.4/api/python/_sources
./site/docs/3.2.1/api/python/_sources
./site/docs/3.4.3/api/python/_sources
./site/docs/3.2.0/api/python/_sources
./site/docs/3.4.2/api/python/_sources
```
After removing them, dangling links like:
https://spark.apache.org/docs/3.5.1/api/python/_sources/user_guide/sql/index.rst.txt are invisible from end users.

We also remove util/build-error-docs.py, which is a tool for doc-gen not for users from in 4.0.0-preview1.

The main goal of this PR is to remove unnecessary publications from doc to reduce the repo size of spark-website

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @HyukjinKwon @cloud-fan @dongjoon-hyun @srowen thanks

**Comment by srowen** [comment]
The idea here is simply that these are unused and so deleting them helps a little bit with the space crunch?
That's OK if so.

How did you find them, out of curiosity?

**Comment by cloud-fan** [comment]
shall we update Spark scripts to clean these files after doc building?

**Comment by yaooqinn** [comment]
> The idea here is simply that these are unused and so deleting them helps a little bit with the space crunch?
That's OK if so.
How did you find them, out of curiosity?


Hi @srowen, I have gained some experience using reStructuredText and Sphinx in other Apache projects, e.g. Apache Kyuubi.

> shall we update Spark scripts to clean these files after doc building?





Hi @cloud-fan https://github.com/apache/spark/pull/47686 is also ready

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
how much space we are saving here?

**Comment by yaooqinn** [comment]
about 10-20M for each version

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Yes, I also double-checked.
```
$ du -h 3.5.1/api/python/_sources
 68K	3.5.1/api/python/_sources/development
148K	3.5.1/api/python/_sources/user_guide/pandas_on_spark
 40K	3.5.1/api/python/_sources/user_guide/sql
208K	3.5.1/api/python/_sources/user_guide
 20K	3.5.1/api/python/_sources/migration_guide
2.9M	3.5.1/api/python/_sources/reference/pyspark.sql/api
3.0M	3.5.1/api/python/_sources/reference/pyspark.sql
180K	3.5.1/api/python/_sources/reference/pyspark.ss/api
196K	3.5.1/api/python/_sources/reference/pyspark.ss
2.5M	3.5.1/api/python/_sources/reference/api
3.0M	3.5.1/api/python/_sources/reference/pyspark.pandas/api
3.1M	3.5.1/api/python/_sources/reference/pyspark.pandas
8.8M	3.5.1/api/python/_sources/reference
4.1M	3.5.1/api/python/_sources/getting_started
 13M	3.5.1/api/python/_sources
```

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Oh, @yaooqinn . It seems that this PR deleted the following.
```
$ COLUMNS=1000 git diff HEAD~1 --stat | grep -v '/api/python/_sources'
 site/docs/4.0.0-preview1/util/build-error-docs.py                                                                                              |   152 ---------
 33288 files changed, 1194166 deletions(-)
```

This PR: 
https://github.com/apache/spark-website/blob/14b7c9e0fb1dd3945672b1fde7fedd4f9b1e585d/site/docs/4.0.0-preview1/util/build-error-docs.py

`asf-site`:
https://github.com/apache/spark-website/blob/4fd6a38/site/docs/4.0.0-preview1/util/build-error-docs.py

**Comment by dongjoon-hyun** [comment]
I manually do the same thing as a test and share it with you as a new PR. The result is not the same with this PR, @yaooqinn . In other words, this PR deletes a wrong file like `util/build-error-docs.py` which is outside of `_sources` and also deletes less number of files. 

- https://github.com/apache/spark-website/pull/545

Screenshot 2024-08-09 at 09 05 35

```
$ find . -name _sources
./site/docs/4.0.0-preview1/api/python/_sources
./site/docs/3.1.2/api/python/_sources
./site/docs/3.3.1/api/python/_sources
./site/docs/3.3.0/api/python/_sources
./site/docs/3.1.3/api/python/_sources
./site/docs/3.4.0/api/python/_sources
./site/docs/3.2.2/api/python/_sources
./site/docs/3.4.1/api/python/_sources
./site/docs/3.2.4/api/python/_sources
./site/docs/3.2.3/api/python/_sources
./site/docs/3.5.0/api/python/_sources
./site/docs/3.1.1/api/python/_sources
./site/docs/3.3.2/api/python/_sources
./site/docs/3.5.1/api/python/_sources
./site/docs/3.3.3/api/python/_sources
./site/docs/3.3.4/api/python/_sources
./site/docs/3.2.1/api/python/_sources
./site/docs/3.4.3/api/python/_sources
./site/docs/3.2.0/api/python/_sources
./site/docs/3.4.2/api/python/_sources

$ find . -name _sources | xargs rm -rf
```

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun 

I update the PR title to mention util/build-error-docs.py too. Spark main has moved it into _plugins already

**Comment by yaooqinn** [comment]
FYI, https://github.com/apache/spark/commit/81948bb61d5f3cbf193b0ba8bddb4afdcb1ec126

**Review by dongjoon-hyun — APPROVED** [review]
Thank you for the fix.

**Comment by dongjoon-hyun** [comment]
> I update the PR title to mention util/build-error-docs.py too. Spark main has moved it into _plugins already

BTW, for the above part, you are unable to delete that file by using https://github.com/apache/spark/commit/81948bb61d5f3cbf193b0ba8bddb4afdcb1ec126  because it's already published Apache Spark 4.0.0-preview1 artifacts.

https://github.com/apache/spark-website/blob/4fd6a38/site/docs/4.0.0-preview1/util/build-error-docs.py

I'm wondering how did you generate this PR initially. Could you revise the PR description by describing the reproducible steps, @yaooqinn ?

**Review by HyukjinKwon — APPROVED** [review]

**Comment by yaooqinn** [comment]
> BTW, for the above part, you are unable to delete that file by using https://github.com/apache/spark/commit/81948bb61d5f3cbf193b0ba8bddb4afdcb1ec126 because it's already published Apache Spark 4.0.0-preview1 artifacts.

I think it's similar to the "_sources" folders. Both of them are accessible via doc releases, but useless to users.

**Comment by dongjoon-hyun** [comment]
Sure, it's similar, of course, @yaooqinn . So, I gave +1 already.

BTW, please revise the PR description about your process to decide them.

> I'm wondering how did you generate this PR initially. Could you revise the PR description by describing the reproducible steps, @yaooqinn ?

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun, updated

**Pull request merged**
