### PR TITLE
add pandas on spark page

### PR DESCRIPTION
**Pull request by MrPowers**
Sorry for the huge PR!

This PR adds a pandas on Spark page to explain the benefits of pandas on Spark.

The [pandas API on Spark docs](https://spark.apache.org/docs/latest/api/python/user_guide/pandas_on_spark/index.html) are great, but they get right into the details and don't provide a high-level overview of why someone should use pandas on Spark.

I am hoping that this page serves as a nice entry-point to the existing pandas API on Spark docs.

### CODE REVIEW

**Comment by xinrong-meng** [comment]
I wanted to add that https://github.com/apache/spark-website/blob/6b0863728b12ee2518af563f6437482642f8b2b4/pandas-on-spark/index.md has the major content to review

**Comment by dongjoon-hyun** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by zhengruifeng** [comment]
LGTM, thanks for working on this

**Review by xinrong-meng — APPROVED** [review]

**Comment by srowen** [comment]
Merged to asf-site

**Pull request closed without merging**
