### PR TITLE
Add Xingbo Jiang to the list of committers

### PR DESCRIPTION
**Pull request by jiangxb1987**

### CODE REVIEW

**Comment by maropu** [comment]
congrats!

**Comment by kiszk** [comment]
Congrats!!

**Comment by jiangxb1987** [comment]
Thanks @maropu @kiszk !

**Comment by vanzin** [comment]
You can even merge the PR yourself now!

**Comment by dongjoon-hyun** [comment]
Great! Congratulations, @jiangxb1987 ! :D

**Comment by HyukjinKwon** [comment]
Yay lgtm

**Comment by jiangxb1987** [comment]
Thanks @vanzin @dongjoon-hyun @HyukjinKwon

**Pull request merged**
