### PR TITLE
Add v3.2.4 docs

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @xinrong-meng . Could you review this PR?
This is simply adding v3.2.4 doc directory.

**Comment by dongjoon-hyun** [comment]
Could you review this, @viirya , @sunchao , @huaxingao ?

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya !

**Comment by xinrong-meng** [comment]
Late LGTM, thanks @dongjoon-hyun !

**Comment by dongjoon-hyun** [comment]
Thanks, @xinrong-meng

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun， late +1

**Pull request merged**
