### PR TITLE
Site update for 2.2.1 release

### PR DESCRIPTION
**Pull request by felixcheung**
Add news and release info for 2.2.1

part 2 of 2 for 2.2.1

### CODE REVIEW

**Comment by srowen** [comment]
@felixcheung your site changes seem fine -- do you want to make more changes and push them, or should I push all of them, including the release process updates?

**Comment by felixcheung** [comment]
thanks @srowen they are all ready, I don't think I have anything else.
For the release process though, it's tied to the release script changes in the spark repo, and might/likely require changes to Jenkins.

**Comment by srowen** [comment]
I pushed this to the site -- you'll need to manually close this because I rebased it @felixcheung 
I'll process the others too.

**Comment by srowen** [comment]
@felixcheung I merged this and https://github.com/apache/spark-website/pull/78 so you should be OK to close them here.

**Pull request closed without merging**
