### PR TITLE
Add 3.0.2 release note and news and update links

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR aims to update our website. I checked the followings are available as of now.
- https://spark.apache.org/docs/3.0.2/
- https://dist.apache.org/repos/dist/release/spark/spark-3.0.2/
- https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.12/3.0.2/
- https://pypi.org/project/pyspark/3.0.2/

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @srowen , @HyukjinKwon , @cloud-fan , @viirya , @holdenk

**Review by viirya — APPROVED** [review]

**Review by srowen — APPROVED** [review]
From a skim, looks good.

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya and @srowen !

**Comment by HyukjinKwon** [comment]
Nice!

**Pull request merged**
