### PR TITLE
Update ml-features.html

### PR DESCRIPTION
**Pull request by DataWanderer**
Potential Enhancement

### CODE REVIEW

**Comment by srowen** [comment]
You're editing the generated documentation from a previous release. We can't do that, but you can edit the docs that will generate these files in a future release. Those are in the spark repo though.
However, this doesn't explain anything about why you are changing this. Please read https://spark.apache.org/contributing.html

**Comment by DataWanderer** [comment]
@srowen  The documentation is out of sync with your example code, I am just enhancing it.

**Comment by srowen** [comment]
Yes, but, if so, this is not how you do it. You need to go to github.com/apache/spark/docs/...

**Comment by DataWanderer** [comment]
@srowen  Why would one update the doc, when the issue in your website https://spark.apache.org/docs/latest/ml-features , also of most recent release 2.4.4

**Comment by srowen** [comment]
Because the released docs are fixed, just like the bits of the release. Unless it's a big problem that makes them unusable, we fix doc problems like we fix bugs and make releases of docs and bugs.
You still haven't even described the issue, though!

**Comment by DataWanderer** [comment]
These dont qualify as bugs, but wasps. Fixing wasps shouldnt need releases !

**Comment by DataWanderer** [comment]
@srowen  so you are saying this is not a wasp in your repository?

**Comment by srowen** [comment]
I answered you above. This is not the place to make the change.

**Pull request closed without merging**
