### PR TITLE
Update documentation.md

### PR DESCRIPTION
**Pull request by packtpartner**
*Make sure that you generate site HTML with `jekyll build`, and include the changes to the HTML in your pull request also. See README.md for more information. Please remove this message.*

### CODE REVIEW

**Review by felixcheung — COMMENTED** [review]
could you explain this PR?

**Comment by packtpartner** [comment]
We have added a new book listing like the previous ones.

**Comment by felixcheung** [comment]
tbh, we don't list every book though. but if you'd like, you will need to run the command in the PR description to re-generate the HTML, otherwise the book will not show up on the web page.

**Comment by srowen** [comment]
@packtpartner just run `jekyll build` and add the updated .html file to this PR.

**Comment by srowen** [comment]
Reopen if you update it

**Pull request closed without merging**
