### PR TITLE
Fix Spark 3.2.0 download URL

### PR DESCRIPTION
**Pull request by gengliangwang**
I made a mistake on the download URL of Spark 3.2.0. This PR is to fix it.

### CODE REVIEW

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
We should really rename the maven profile name...

**Comment by yaooqinn** [comment]
> We should really rename the maven profile name...

😂

**Comment by gengliangwang** [comment]
There are some discussions about this on dev list: https://www.mail-archive.com/dev@spark.apache.org/msg28025.html
The conclusion was to make it at Spark 3.3.0.  
We could try renaming the tarball on finalizing the release, but I was using release script...
Should we keep it as it is? Or figure out a way to fix it? cc @dongjoon-hyun @sunchao

**Comment by srowen** [comment]
Change at Spark 3.3 IMHO. It's just a naming thing. hadoop-3.2 really means "3.2 or later" so it's not crazy

**Comment by sunchao** [comment]
I'll pick up https://github.com/apache/spark/pull/30891 again soon and make sure we'll get this done before Spark 3.3.0

> Should we keep it as it is? Or figure out a way to fix it? 

I think we can fix this in the same PR above, perhaps by just changing `make-distribution.sh`.

**Comment by srowen** [comment]
Let's not make the release differ from the profiles, I think. We can rename the profile and leave hadoop-3.2 as a no-op profile. By 3.3.0, who knows, maybe we're on 3.4 or something

**Comment by dongjoon-hyun** [comment]
Thank you for the fix, @gengliangwang .

**Pull request merged**
