### PR TITLE
Fix title for spark 3.5.1 PySpark doc

### PR DESCRIPTION
**Pull request by panbingkun**
The pr aims to fix `title` for spark `3.5.1` PySpark doc.

As discussed by another PR:
https://github.com/apache/spark-website/pull/507#issuecomment-1984987418

### CODE REVIEW

**Comment by panbingkun** [comment]
image

**Comment by panbingkun** [comment]
cc @HeartSaVioR @dongjoon-hyun @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by srowen** [comment]
We still want to merge this right?

**Comment by HyukjinKwon** [comment]
Yup, merging

**Comment by HyukjinKwon** [comment]
Merged to asf-site.

**Pull request closed without merging**
