### PR TITLE
update the canonical link, due to a change in some addresses in the latest version of the document

### PR DESCRIPTION
**Pull request by panbingkun**
The pr is followup https://github.com/apache/spark-website/pull/482.

https://github.com/apache/spark-website/pull/482#issuecomment-1765322679
As discussed above, due to changes in some document addresses after version `3.3.0`, `the canonical link` is incorrect. We are now correcting it.

Base on rule:
For file that do not exist in version `latest`, delete the corresponding ref and update it for the rest.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @allanf-db @HyukjinKwon @zhengruifeng @allisonwang-db @srowen

**Review by allisonwang-db — APPROVED** [review]
Thanks for updating this!

**Review by HyukjinKwon — APPROVED** [review]
Did not take a close look but seems fine

**Comment by allisonwang-db** [comment]
This should be good to go. I've checked the canonical link for 3.1.1 gruopBy doc is correctly pointing to the latest one :)

**Comment by panbingkun** [comment]
In order to prevent possible merge conflicts, after this PR, I will add `Matomo analytics` to the already published HTML document.

**Comment by allisonwang-db** [comment]
Sounds good. cc @HyukjinKwon this one should be ready to go

**Comment by HyukjinKwon** [comment]
Merged to asf-site.

**Pull request closed without merging**
