### PR TITLE
Hide TimestampNTZ from Apache Spark 3.2.2 docs

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
This is a follow-up for the discussion at https://github.com/apache/spark/pull/35313

**Review by sarutak — APPROVED** [review]
@dongjoon-hyun Thank you for following up! It LGTM.

**Review by gengliangwang — APPROVED** [review]
Thank you!

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @sarutak , @gengliangwang , @viirya .

**Pull request merged**
