### PR TITLE
Additional typo fixes

### PR DESCRIPTION
**Pull request by fredster33**
Note: there's a typo in my commit, it's supposed to spell "fixes".

### CODE REVIEW

**Comment by srowen** [comment]
I may be blind but don't see 'fixes'?

**Comment by fredster33** [comment]
Markdown and Scala should be capitalized as proper nouns, IMO.

**Comment by srowen** [comment]
That's fine, but what is your first comment referring to?

**Comment by fredster33** [comment]
This.

**Comment by fredster33** [comment]
The "fies".

**Comment by srowen** [comment]
Oh, the commit message. That's fine, doesn't matter.

**Pull request closed without merging**
