### PR TITLE
[SPARK-23946] Fix 2.3.0 ScalaDocs are linked to the wrong source code

### PR DESCRIPTION
**Pull request by wangyum**
Fix 2.3.0 ScalaDocs are linked to the wrong source code.

### CODE REVIEW

**Comment by wangyum** [comment]
OK, close it.

**Comment by HyukjinKwon** [comment]
? @wangyum why did you close this one?

**Review by HyukjinKwon — APPROVED** [review]
Output itself seems fine.

@wangyum do you maybe know if we need to take an action to Spark itself? I haven't taken a close look yet but SPARK-23732 describes an issue within Spark too.

**Comment by HyukjinKwon** [comment]
btw I think you don't have to link a JIRA in the title tho.

**Comment by felixcheung** [comment]
the links look wrong but these doc html is generated automatically from the spark source - if it's wrong some script might need to be changed/fixed

**Comment by HyukjinKwon** [comment]
Yup, but this PR itself seems still a proper improvement tho. It should be best to fix the script if there's something wrong but if that's pending, it might be okay to go ahead as is.

cc @sameeragarwal who made the release and @mgaido91 who looks made a change to the script.

**Comment by mgaido91** [comment]
@HyukjinKwon sorry but I am not sure about which script you're talking about. Anyway, the change seems fine.

**Comment by HyukjinKwon** [comment]
I am sorry, ignore it .. It was my stupid mistake .. I meant @jodersky for https://github.com/apache/spark/commit/ed775042cceb61a0566502e1306ac3c70f4a6a5f and https://issues.apache.org/jira/browse/SPARK-23732. Will try to have some time to take a look anyway.

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
@wangyum, thanks for working on this.

**Pull request closed without merging**
