### PR TITLE
Fix the CSS of Spark 3.5.0 doc's generated tables

### PR DESCRIPTION
**Pull request by gengliangwang**
After https://github.com/apache/spark/pull/40269, there is no border in the generated tables of Spark doc(for example,  [sql-ref-ansi-compliance.html](https://spark.apache.org/docs/latest/sql-ref-ansi-compliance.html)) . Currently only the doc of Spark 3.5.0 is affected. 
This PR is to apply the changes in https://github.com/apache/spark/pull/44096 on the current Spark 3.5.0 doc by
1. change the `site/docs/3.5.0/css/custom.css` 
2. Execute `sed  -i ''  's/table class="table table-striped"/table/' *.html` under `site/docs/3.5.0/` directory.

This should be a safe change. I have verified it on my local env.

### CODE REVIEW

**Review by viirya — APPROVED** [review]

**Comment by gengliangwang** [comment]
@viirya Thanks for the review. I am merging it now and will double-check on the website.

**Comment by viirya** [comment]
Thank you @gengliangwang

**Comment by gengliangwang** [comment]
I confirmed that the changes work as expected!

**Comment by viirya** [comment]
Thanks @gengliangwang for confirming that.

**Pull request merged**
