### PR TITLE
Add Yikun Jiang to committers

### PR DESCRIPTION
**Pull request by Yikun**

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
Congrats!

**Comment by mridulm** [comment]
Congratulations !

**Comment by Yikun** [comment]
@mridulm @HyukjinKwon @srowen Thanks all!

**Comment by yaooqinn** [comment]
Congrats!

**Comment by zhengruifeng** [comment]
@Yikun Congrats!

**Comment by dongjoon-hyun** [comment]
Congrats! :)

**Comment by Yikun** [comment]
@dongjoon-hyun @zhengruifeng @yaooqinn Thanks!

**Pull request closed without merging**
