### PR TITLE
[WIP] DO NOT MERGE, TESTING GITHUB ACTION

### PR DESCRIPTION
**Pull request by attilapiros**

### CODE REVIEW

**Comment by attilapiros** [comment]
The 1st case, markdown without corresponding HTML, is [failed with the expected error](https://github.com/apache/spark-website/pull/310/checks?check_run_id=1957994291):
```
Not all documentation was generated and/or not the right Jekyll version was used! Modified / untracked files (excluding sitemap.xml):
site/community.html
Git diff (excluding sitemap.xml):
diff --git a/site/community.html b/site/community.html
index c7b3d0369..e6a6d41b2 100644
--- a/site/community.html
+++ b/site/community.html
@@ -207,7 +207,8 @@
 
 <h4>StackOverflow</h4>
 
-<p>For usage questions and help (e.g. how to use this Spark API), it is recommended you use the 
+<p>Testing. Testing &#8230;. 
+For usage questions and help (e.g. how to use this Spark API), it is recommended you use the 
 StackOverflow tag <a href="https://stackoverflow.com/questions/tagged/apache-spark"><code class="language-plaintext highlighter-rouge">apache-spark</code></a> 
 as it is an active forum for Spark users&#8217; questions and answers.</p>
 
Error: Process completed with exit code 1.
```

**Comment by attilapiros** [comment]
the 2nd case with an extra file without corresponding generated HTML also [failed with the expected error](https://github.com/apache/spark-website/pull/310/checks?check_run_id=1958057595):
```
Not all documentation was generated and/or not the right Jekyll version was used! Modified / untracked files (excluding sitemap.xml):
site/new_file.html site/community.html
```

**Comment by attilapiros** [comment]
Adding the missing HTMLs lead to a [passed the test](https://github.com/apache/spark-website/pull/310/checks?check_run_id=1958118235).

**Comment by attilapiros** [comment]
@HyukjinKwon The test was successful, I am closing this.

**Comment by HyukjinKwon** [comment]
Thanks man :-)

**Pull request closed without merging**
