### PR TITLE
Add 2.4.5 docs and update `latest` symlink

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This adds the voted `2.4.5` document and update `latest` symlink only.

- https://dist.apache.org/repos/dist/dev/spark/v2.4.5-rc2-docs

For the rest of update, I will do in another PR.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @srowen .
Could you review this PR?

**Comment by dongjoon-hyun** [comment]
Hi, @dbtsai .
Could you review this?

**Comment by dbtsai** [comment]
LGTM. Thanks.

**Comment by dongjoon-hyun** [comment]
Thank you!

**Pull request merged**
